### ISSUE TITLE
After update packages: Undefined variable: b:node_root

### ISSUE THREAD

**Issue by carlitux** [Shougo/deoplete.nvim#176] opened 2016-02-15 21:21 UTC
```bash
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/carlitux/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 55, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/carlitux/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 90, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/carlitux/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/carlitux/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 52, in gather_candidates
[deoplete]     '"fnamemodify(v:val, \\":p\\")")') if exists(x)]:
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 127, in eval
[deoplete]     return self._session.request('vim_eval', string, async=async)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/common.py", line 230, in request
[deoplete]     return walk(self._in, self._session.request(name, *args, **kwargs),
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 90, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E121: Undefined variable: b:node_root'
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by zchee** [comment] 2016-02-15 23:51
@carlitux Hi, Thanks issue.

I will debug by reference to your error log, but information too few...
Could you post you're `init.vim` and sample files?

**Comment by carlitux** [comment] 2016-02-16 02:54
@schee https://github.com/linkux-it/linkux-dev/blob/master/conf/osx/nvimrc that is

**Comment by carlitux** [comment] 2016-02-16 03:38
Also ultisnips is not working... some sources not working

**Comment by Shougo** [comment] 2016-02-16 13:35
@carlitux Please use latest deoplete.
And please read the CONTRIBUTION.md.

https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

Your init.vim is too long and hard to reproduce.

**Comment by carlitux** [comment] 2016-02-16 13:40
@Shougo sorry I forgot to update this... I did an hour ago and it is working again... but still having the error... only it is happens on a large project:

OS: OSx
Version:
```
:version
NVIM v0.1.3-100-g5af9ae9
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector
-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160216-57346-19bt06y/build/config -I/tmp/neovim20160216-57346-19bt06y/src -I/tmp/neovim20160216-57346-19bt0
6y/deps-build/usr/include -I/tmp/neovim20160216-57346-19bt06y/deps-build/usr/include -I/tmp/neovim20160216-57346-19bt06y/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160216-57346-19bt06y/deps-build/us
r/include -I/tmp/neovim20160216-57346-19bt06y/deps-build/usr/include -I/tmp/neovim20160216-57346-19bt06y/deps-build/usr/include -I/tmp/neovim20160216-57346-19bt06y/deps-build/usr/include -I/usr/local/opt/
gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160216-57346-19bt06y/build/src/nvim/auto -I/
tmp/neovim20160216-57346-19bt06y/build/include
Compiled by carlitux@lcruzc.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

I will debug and try to give more information of it.

**Comment by Shougo** [comment] 2016-02-16 19:58
> @Shougo sorry I forgot to update this... I did an hour ago and it is working again... but still having the error... only it is happens on a large project:

Please upload the new error message.
I think it is different.

**Comment by carlitux** [comment] 2016-02-16 21:42
@Shougo is same error really but now I can autocomplete.

**Comment by Shougo** [comment] 2016-02-16 21:55
@carlitux I think your deoplete is not the latest version.
Please update it.

**Comment by carlitux** [comment] 2016-02-16 22:04
@Shougo this new update removed it!... thanks.

**Comment by Shougo** [comment] 2016-02-16 22:08
The problem is resolved?
I want to close the issue.

**Comment by carlitux** [comment] 2016-02-16 22:09
yeah I am not getting the error anymore.

**Closed** 2016-02-16 22:15 UTC
Labels: cannot reproduce, reproduce ways
