### ISSUE TITLE
After using toggle.vim deoplete inserts "<Plug>_" in command line mode

### ISSUE THREAD

**Issue by copy** [Shougo/deoplete.nvim#610] opened 2018-01-15 18:46 UTC
# Problems summary

After using `+` from toggle.vim and using `:` to switch to command line mode, the text `<Plug>_`  is inserted into the command line.

## Expected

No text should be inserted into the command line.

## Environment Information

 * deoplete version(SHA1): b164eb8

 * OS: Linux

 * neovim/Vim version: v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only): All okay.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/.config/nvim/bundle/deoplete.nvim/
set runtimepath+=~/.config/nvim/bundle/toggle/
set runtimepath+=~/.config/nvim/bundle/truefalse-completion/

let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 1000 " Makes it easier to reproduce, but not necessary
```

- Get toggle.vim from http://www.vim.org/scripts/script.php?script_id=895 and install it to `~/.config/nvim/bundle/toggle/plugin/toggle.vim`.

- Get the minimal async completor from [here](https://gist.github.com/copy/0ada90677b950de3c2273b874a3265ef) and install it to `~/.config/nvim/bundle/truefalse-completion/rplugin/python3/deoplete/sources/truefalse.py`

## The reproduce ways from neovim/Vim starting (Required!)

 1. Write `False` into the buffer
 2. Type `+` in normal mode to change the `False` to `True`
 3. Immediately after, type `:`
4. The `<Plug>_` text appears after a second

The timing is tricky, if it doesn't work try waiting a split second between `+` and `:`.

## Screen shot (if possible)

![screenshot_2018-01-15_12-34-51](https://user-images.githubusercontent.com/1816456/34956942-052b6694-f9f1-11e7-8740-112a068d4e58.png)

## Upload the log file

[log_py3_rplugin.log](https://github.com/Shougo/deoplete.nvim/files/1632676/log_py3_rplugin.log)

Note: In practise this bug occurs rarely, but it does happen even with a non-contrived configuration. It mostly results in files named `<Plug>_` being written, because I type `:w` quickly and the text is inserted before the return.

**Comment by Shougo** [comment] 2018-01-16 02:14
I have tested your vimrc, but I cannot reproduce the problem.

**Comment by Shougo** [comment] 2018-01-16 02:19
I won't fix the problem.  Because I cannot reproduce it.
Sorry.

**Closed by Shougo** 2018-01-16 02:19 UTC
Labels: cannot reproduce

**Comment by Shougo** [comment] 2018-01-16 02:21
Gave up.

Hint:  You can debug the problem.

`<Plug>_` inserting is implemented in `s:do_complete()`.
And `mode()` check is already implemented.  So it should work.
I don't know why it does not work in your enviroment.

https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/handler.vim#L43

**Comment by copy** [comment] 2018-01-16 02:45
> I won't fix the problem. Because I cannot reproduce it. 

Did you install the truefalse completion plugin? It should complete `True` and `False` in an empty file in insert mode.

> <Plug>_ inserting is implemented in s:do_complete().
> And mode() check is already implemented. So it should work.
> I don't know why it does not work in your enviroment.

It checks `get(context, 'event', '') !=# 'InsertEnter' && mode() !=# 'i'`, so on my system `get(context, 'event', '')` is `'InsertEnter'`. Do you know why the mode check is skipped for this event?

**Comment by Shougo** [comment] 2018-01-16 02:54
> Do you know why the mode check is skipped for this event?

Because, in `InsertEnter` `mode()` is `n`.

> Did you install the truefalse completion plugin? It should complete True and False in an empty file in insert mode.

Yes.  But it does not work in normal mode.
Please see your the reproduce ways.

> Type + in normal mode to change the False to True

Why deoplete works in normal mode?
I don't understand and I cannot reproduce the behavior.

**Comment by Shougo** [comment] 2018-01-16 03:04
Please test below patch.

```diff
diff --git a/autoload/deoplete/handler.vim b/autoload/deoplete/handler.vim
index 06080e6..f484dec 100644
--- a/autoload/deoplete/handler.vim
+++ b/autoload/deoplete/handler.vim
@@ -39,8 +39,11 @@ endfunction

 function! s:do_complete(timer) abort
   let context = g:deoplete#_context
+  let event = get(context, 'event', '')
+  let modes = ['i', 'n']
   if s:is_exiting()
-        \ || (get(context, 'event', '') !=# 'InsertEnter' && mode() !=# 'i')
+        \ || (event !=# 'InsertEnter' && mode() !=# 'i')
+        \ || (event ==# 'InsertEnter' && index(modes, mode()) < 0)
     call s:completion_timer_stop()
     return
   endif
```

**Comment by copy** [comment] 2018-01-16 03:09
@Shougo The patch fixes the problem, thanks!

**Comment by Shougo** [comment] 2018-01-16 03:10
OK.  I will fix it later.

**Comment by Shougo** [comment] 2018-01-16 14:57
Fixed.

**Comment by Cypher1** [comment] 2023-08-18 05:45
Just FYI I'm experiencing this again, disabling deoplete for now as it's too distracting and annoying (it breaks delete in insert mode for me). Seems to occur most when deleting a `)` (close parenthesis).

**Comment by Shougo** [comment] 2023-08-18 05:56
I recommend for you to use ddc.vim instead.

deoplete is too old plugin.

**Comment by Cypher1** [comment] 2023-08-18 09:54
Thanks @Shougo !
