### ISSUE TITLE
eliminate flicker

### ISSUE THREAD

**Issue by zhou13** [Shougo/deoplete.nvim#284] opened 2016-06-03 23:54 UTC
Hi Shougo,

In my experience, the cursor and the popup completion menu sometimes still flickers using neovim with deoplete.  I think this maybe be a bug in neovim or deoplete.  I would like to help to fix this problem. If this is a bug of neovim, i.e., the redraw is triggered when it should not be, then it should be fixed.  If the flicker is caused by the cursor movement in deoplete, is it possible to totally eliminate it by adding a feature to neovim to temporary disable screen redraw?  Do you have any idea what operation causes the flicker in deoplete?

**Comment by Shougo** [comment] 2016-06-05 08:40
Why do you ignore the issue template?
You must create the reproduce ways from neovim starting.
The flicker problem should be fixed, Yes.
But your information is very few.  I cannot reproduce it.

**Comment by zhou13** [comment] 2016-06-05 10:13
The reason I did not give the reproduce way is because it is hard: the flicker only became obvious when you load a lot of plugins and edit a large file. But I can give a systemic way to reproduce one of the cases.

1.  Apply this patch to neovim
````
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 202c566..b27fce4 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -415,6 +415,8 @@ static void tui_eol_clear(UI *ui)
 
 static void tui_cursor_goto(UI *ui, int row, int col)
 {
+  fprintf(stderr, "tui_cursor_goto %d %d\n", row, col);
+  fflush(stderr);
   TUIData *data = ui->data;
   ugrid_goto(&data->grid, row, col);
   unibi_goto(ui, row, col);
@@ -575,6 +577,8 @@ static void tui_update_bg(UI *ui, int bg)
 
 static void tui_flush(UI *ui)
 {
+  fprintf(stderr, "tui_flush\n");
+  fflush(stderr);
   TUIData *data = ui->data;
   UGrid *grid = &data->grid;
````

2.  minimum vimrc:
````
call dein#begin(expand('xxxxxxxxxxxxxx'))
call dein#add('Shougo/deoplete.nvim')
call dein#add('zchee/deoplete-jedi')
call dein#end()
````

3. execute `bin/nvim 1.py 2> debug.txt`.  Execute `tail -f debug.txt` in another terminal.

4. enter `iimport` in nvim

5.  in `debug.txt`, you will find such information
````
tui_flush
tui_flush
tui_flush
tui_flush
tui_flush
tui_flush
tui_flush
tui_flush
tui_cursor_goto 1 0
tui_cursor_goto 0 2
tui_flush
tui_flush
tui_flush
tui_flush
tui_flush
tui_flush
tui_flush
tui_cursor_goto 1 0
tui_cursor_goto 1 0
tui_flush
tui_flush
tui_cursor_goto 0 3
tui_flush
tui_flush
tui_flush
tui_flush
tui_cursor_goto 1 0
tui_cursor_goto 1 0
tui_flush
tui_flush
tui_cursor_goto 0 4
tui_flush
tui_flush
tui_flush
tui_flush
tui_cursor_goto 1 0
tui_cursor_goto 1 0
tui_flush
tui_flush
tui_cursor_goto 0 5
tui_flush
tui_flush
tui_flush
tui_flush
tui_cursor_goto 0 0
tui_cursor_goto 1 0
tui_cursor_goto 1 0
tui_flush
tui_flush
tui_cursor_goto 0 6
````

You can see that there are two `tui_flush` between `tui_cursor_goto 1 0` and `tui_cursor_goto 0 x`.  So after user inputs a char, he may see the cursor going to (1,0) and then go back to (0,x), which causes flicker.  Only when workload of nvim is heavy, this becomes obvious because `tui_flush` and the routine that calls it may need to take some time to finish.

**Comment by Shougo** [comment] 2016-06-05 10:17
You should create new issue in neovim issues.
Similar issuehttps://github.com/neovim/neovim/issues/4847

**Comment by zhou13** [comment] 2016-06-05 10:19
I am not sure how to reproduce it without `Shougo/deoplete.nvim`.  Any idea?

**Comment by Shougo** [comment] 2016-06-05 10:20
neovim/neovim#4847 is the redraw issue.
If the redraw occurs, neovim will be flick.

**Comment by zhou13** [comment] 2016-06-05 10:21
However, it is about the redraw of statusline.  In my case, it is not becuase you can see that the cursor never goes to the statusline.

**Comment by Shougo** [comment] 2016-06-05 10:22
@zhou13 It is not just statusline redraw.
Please read the whole issue.

> From poking in Neovim's source it seems to happen through normal_redraw in normal_check.

**Comment by zchee** [comment] 2016-06-05 10:23
@zhou13 hi, it's problem only deoplete-jefi? or same it in other sources?

**Comment by zhou13** [comment] 2016-06-05 10:27
@zchee I think it is in every source, and it is very like that this is in every call of the nvim's completion function but I don't know which one does deoplete use.

**Comment by zchee** [comment] 2016-06-05 10:58
@zhou13 As @Shougo said, I think also it's issue caused by `redraw`
but deoplete-jedi code was aggressive changed recently, so I asked just to be sure.

BTW, When does it flick? If that timing when select word in complete list, it can be somewhat improve using unofficial patch.

**Comment by Shougo** [comment] 2016-06-07 11:50
I have optimized deoplete implementation.
Closing.

**Closed** 2016-06-07 11:49 UTC
Labels: cannot reproduce, reproduce ways

**Comment by blueyed** [comment] 2016-12-06 01:04
For reference: https://github.com/Shougo/deoplete.nvim/commit/603a4a6625833fff8d3955145c30ef89172dbe1e
