### ISSUE TITLE
How to configure the size of the shown docstring in the preview window

### ISSUE THREAD

**Issue by hwalinga** [Shougo/deoplete.nvim#1044] opened 2019-12-01 19:07 UTC
# Problems summary

The docstring in the preview window is truncated to a too small size to be useful. I couldn't find a way to configure this to a larger size.

## Expected

It seems the size is now only 40 characters. I think the default can be a lot more or some pointer in the documentation on how to change this.

## Environment Information

 * deoplete version (SHA1):

41ab306416a951be661622d7b0d174fe74f84f7e

* deoplete-jedi version (SHA1):

f442e98c6c81649985f1cfc735fb4d25f3e27010

 * OS:

MX Linux 19 (Debian 10)

 * neovim/Vim `:version` output:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-0.3.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-0.3.8/build/config -I/build/neovim-0.3.8/src -I/usr/include -I/build/neovim-0.3.8/build/src/nvim/auto -I/build/neovim-0.3.8/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='rxvt-xpm'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/hielke/.linuxbrew/Cellar/pyenv/1.2.15/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/hielke/.pyenv
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/hielke/.venv/py3/bin/python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/hielke/.linuxbrew/Cellar/pyenv/1.2.15/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/hielke/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - WARNING: Your virtualenv is not set up optimally.
    - ADVICE:
      - Create a virtualenv specifically for Neovim and use `g:python3_host_prog`.  This will avoid the need to install the pynvim module in each virtualenv.
  - INFO: $VIRTUAL_ENV matches executable
  - INFO: Executable: /home/hielke/.venv/py3/bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.4.0
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.15.2
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/bundle')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

Plug 'deoplete-plugins/deoplete-jedi'

call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#show_docstring = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

nvim test.py

Type:

from itertools import ch

Press ^n

The only text in the preview window is now: 

```
chain(*iterables: Iterable[_T])

chain(*...
```

Seems like it is limited by about 40 characters. 

## Attempts to resolve

I tried to change some values like `max_kind_width`, `max_info_width`, and `max_menu_width` from source.py and `g:deoplete#sources#jedi#statement_length`, but it did not had any effect. 

## Screenshot (if possible)

https://i.imgur.com/NwdptGZ.png

**Comment by Shougo** [comment] 2019-12-01 23:59
I have tested it, but I don't reproduce your problem.

**Comment by Shougo** [comment] 2019-12-02 00:01
And the truncated is fixed by:

```vim
call deoplete#custom#source('jedi', 'max_info_width', 0)
```

**Closed by Shougo** 2019-12-02 00:01 UTC

**Comment by hwalinga** [comment] 2019-12-02 20:09
Interesting, it did got fixed when I set it to zero. Thanks for that. However, any other value is ignored. Even if I set it to something very large. 

Since you unfortunately cannot reproduce it, I digged in the code myself a bit. I found that in child.py there is a line that states: `ctx['max_info_width'] = min(source.max_info_width, ctx['max_info_width'])`. 

A print statement showed my that source.max_info_width is the expected default 200, but that ctx["max_info_width"] is an unexpected low value. I also discovered that this value is different depending on the window size. (Unfortunate even in larger windows this value is unusable small.) 

I looked where ctx comes from and it seems to come from a vim function called `get_syn_names`. I am not so proficient with vimscript, but in that function is a comment that says: `Note: synstack() seems broken in concealed text.` Perhaps, that is the issue?

I also could produce the issue described here on a fresh install of Debian 10.

**Comment by Shougo** [comment] 2019-12-02 23:40
OK.  I get it.
I have fixed the `max_info_width` initialization problem.

**Comment by Shougo** [comment] 2019-12-02 23:48
> Unfortunate even in larger windows this value is unusable small.

I don't reproduce the problem though.

**Comment by hwalinga** [comment] 2019-12-03 01:42
It probably does not help very much, but here is a screencast: 

http://hwalinga.pythonanywhere.com/static/deoplete-docstring.gif

**Comment by Shougo** [comment] 2019-12-03 01:50
I think the problem is fixed, if it is not fixed well, you can create the PR.
It is open source.

**Comment by Shougo** [comment] 2019-12-03 02:01
And have you tested the latest version?
The screencast seems older version.

**Comment by hwalinga** [comment] 2019-12-03 16:27
Yes, it works as intended now. Thank you very much.
