### ISSUE TITLE
Problem expanding abbreviations with melanc/delimitMate.

### ISSUE THREAD

**Issue by kwinczek** [Shougo/deoplete.nvim#234] opened 2016-03-21 20:41 UTC
# Problems summary

https://github.com/melanc/delimitMate breaks abbreviation expansion with complete pop up window visible. It expands as expected once completion is finished.

## Expected

Abbreviation to be expanded after space in insert mode – regardless to whether completion window is visible or not.

## Environment Information

 * OS: Mac OS X 10.11.3
 * Neovim version: 0.1.2

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/minimal-plugged')

Plug 'Shougo/deoplete.nvim'
Plug 'melanc/delimitMate'

call plug#end()
filetype plugin indent on
syntax enable

set omnifunc=syntaxcomplete#Complete
set completeopt=longest,menuone,preview,noinsert

iabbr <silent> tst TEST TEST

let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1
let delimitMate_expand_inside_quotes = 1
let delimitMate_jump_expansion = 1
let delimitMate_balance_matchpairs = 1

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1
let g:deoplete#file#enable_buffer_path = 1

call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
autocmd CompleteDone * pclose!

inoremap <expr> <CR>
    \ pumvisible() ? deoplete#mappings#close_popup() :
    \ "\<CR>"

inoremap <silent><expr> <Tab>
    \ pumvisible() ? "\<C-n>" :
    \ deoplete#mappings#manual_complete()

inoremap <silent><expr> <S-Tab>
    \ pumvisible() ? "\<C-p>" :
    \ deoplete#mappings#manual_complete()
```

## The reproduce ways from neovim starting (Required!)

 1. In insert mode type 'tst' immediately followed by space - abbreviation does not get expanded.
 2. In insert mode type 'tst', hit enter and then space - abbreviation gets expanded as expected.

**Comment by kwinczek** [comment] 2016-03-21 21:16
Please ignore for now. Something to do with delimate.

**Comment by kwinczek** [comment] 2016-03-22 17:18
Reopening the issue as I figured out it is delimitMate presence causing it. I am not posting it here, not on delimitMate project page because it used to work. I did pin it down to 39272876af2404fb6c02089fae10d87d5c7fb130 breaking it.

**Comment by zchee** [comment] 2016-03-22 17:31
@kwinczek Thanks issue.
I'll test it instead of @Shougo.

**Comment by zchee** [comment] 2016-03-22 17:35
@kwinczek BTW, How did you install neovim? Homebrew? self-build?
Please post a full neovim version.

In neovim,
```vim
:version
```

**Comment by kwinczek** [comment] 2016-03-22 18:08
```vim
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-co
lor=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160316-89107-o8qt9v/neovim-0.1.2/build/config -I/tmp/neovim20160316-89107-o8qt9v/neovim-0.1.2/src -I/tmp/neovim20160316-89107-o8qt9
v/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160316-89107-o8qt9v/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160316-89107-o8qt9v/neovim-0.1.2/deps-build/usr/include/luajit-2.0 -I/tmp/neovim
20160316-89107-o8qt9v/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160316-89107-o8qt9v/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160316-89107-o8qt9v/neovim-0.1.2/deps-build/usr/include -I/t
mp/neovim20160316-89107-o8qt9v/neovim-0.1.2/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160316-89107-o8qt9v/neovim-0.1.2/build/src/nvim/auto -I/tmp
/neovim20160316-89107-o8qt9v/neovim-0.1.2/build/include
Compiled by kwinczek@raven

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.2/share/nvim"
```

For the records. Will try HEAD of neovim now.

**Comment by zchee** [comment] 2016-03-22 18:11
@kwinczek Thanks :)

Maybe this issue not related `K_EVENT` issue, but Please re-try use `HEAD` version and post result.

**Comment by kwinczek** [comment] 2016-03-22 18:30
@zchee It works nicely with latest version of delimitMate, deoplete and nvim built from HEAD. Not sure whether issue should be closed though…

**Comment by zchee** [comment] 2016-03-22 18:36
@kwinczek Oh, Just wait a close.
I will investigate the cause.

Just in case, you work perfectly in HEAD?

**Comment by kwinczek** [comment] 2016-03-22 19:36
Exactly, HEAD - OK, 0.1.2 - broken. This is with latest deoplete.

**Comment by zchee** [comment] 2016-03-22 19:54
@kwinczek Thanks. I'll debug it.

===

BTW, Shougo might close this issue.

**Comment by Shougo** [comment] 2016-03-22 21:02
If neovim HEAD is OK, this is not deoplete problem.

**Closed** 2016-03-22 21:02 UTC

**Comment by zchee** [comment] 2016-03-22 21:03
@kwinczek Maybe caused by `K_EVENT`.
Thanks information.

**Comment by kwinczek** [comment] 2016-03-22 22:31
@Shougo Fair enough, but what is interesting is the fact that it used to work and got broken by specific change in deoplete's code.

Thanks for your help guys!

**Comment by kwinczek** [comment] 2016-04-18 21:14
Still having that problem with nvim 0.1.3 this time.

**Comment by Shougo** [comment] 2016-04-18 21:31
@kwinczek 0.1.3 is not HEAD.
And you can check it by `git bisect`.

**Comment by kwinczek** [comment] 2016-04-19 05:43
Bisect on deoplete? Did that, breaking commit is once again 39272876af2404fb6c02089fae10d87d5c7fb130.

**Comment by Shougo** [comment] 2016-04-19 22:50
I have reproduced it .  Please remove below line.  It conflicts with deoplete.
I don't know why the previous deoplete is working.

```vim
autocmd CompleteDone * pclose!
```

**Comment by kwinczek** [comment] 2016-04-20 05:53
Removing that does not help in my case. What is causing the problem is `delimitMate_expand_space` set to `1`. I would really like to keep that enabled. Can you think of any work around?

Thanks!

**Comment by Shougo** [comment] 2016-04-20 20:26
Yes, it is delimitMate problem.
It checks the popup menu.  Please read it.

https://github.com/Raimondi/delimitMate/blob/master/plugin/delimitMate.vim#L265
