### ISSUE TITLE
Completion menu show up time is long if a source is slow

### ISSUE THREAD

**Issue by jsfaint** [Shougo/deoplete.nvim#645] opened 2018-02-08 08:41 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
 I compared deoplete with ncm.
In ncm, if a source is slow, it will not impact the completion menu show up time.
But in ncm, if a source is slow, it will impact the completion menu show up time.

## Expected
If some source is slow, the faster source should show in completion menu first.

## Environment Information

 * deoplete version(SHA1):
c145a7fea45850f5e19151f9748a0dc8e8e92329

 * OS:
windows 10

 * neovim/Vim version:
NVIM 0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    python2 not found in search path or not executable.
    python2.7 not found in search path or not executable.
    python2.6 not found in search path or not executable.
    C:\Users\jia.sui\AppData\Local\Programs\Python\Python36\python is Python 3.6 and cannot provide Python 2.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Users\jia.sui\AppData\Local\Programs\Python\Python36\python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:/Users/jia.sui/AppData/Local/Programs/Python/Python36/python.exe"
  - INFO: Executable: C:/Users/jia.sui/AppData/Local/Programs/Python/Python36/python.exe
  - INFO: Python3 version: 3.6.4
  - INFO: python.exe-neovim version: 0.2.1
  - OK: Latest python.exe-neovim is installed: 0.2.1

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node provider (optional)
  - INFO: Node: v8.9.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let s:rc_path = fnamemodify(expand('<sfile>'), ':h')

let s:vimplug = expand(s:rc_path . '/autoload')

if empty(glob(s:vimplug . '/plug.vim'))
  execute '!git clone --depth=1 https://github.com/junegunn/vim-plug' s:vimplug
  augroup vimrc
    autocmd VimEnter * PlugInstall
  augroup END
endif

call plug#begin(s:rc_path . '/plugged')

"Completion
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

"deoplete.nvim
if (has('nvim') || v:version >= 800) && has('python3')
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#num_processes = 20
endif
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Add a time.sleep(10) in `gather_candidates()` tag.py
  ```diff
diff --git a/rplugin/python3/deoplete/source/tag.py b/rplugin/python3/deoplete/source/tag.py
index 1dcec7f..7a32695 100644
--- a/rplugin/python3/deoplete/source/tag.py
+++ b/rplugin/python3/deoplete/source/tag.py
@@ -33,6 +33,8 @@ class Source(Base):
         self._make_cache(context)

     def gather_candidates(self, context):
+        import time
+        time.sleep(10)
         self._make_cache(context)
         candidates = []
         for c in self._cache.values():
  ```
 2. Add
 2. Open any files, then type something
 3. The completion window will show up after 10s

## Screen shot (if possible)
![deoplete](https://user-images.githubusercontent.com/571829/35963481-c719c398-0cef-11e8-982e-a43f9af490f1.gif)

## Upload the log file
[deoplete.log](https://github.com/Shougo/deoplete.nvim/files/1706274/deoplete.log)

**Comment by Shougo** [comment] 2018-02-08 09:06
Reproduced.

**Comment by Shougo** [comment] 2018-02-08 09:27
```vim
diff --git a/rplugin/python3/deoplete/parent.py b/rplugin/python3/deoplete/parent.py
index 97cb510..b03ea7d 100644
--- a/rplugin/python3/deoplete/parent.py
+++ b/rplugin/python3/deoplete/parent.py
@@ -88,5 +88,5 @@ class Parent(logger.LoggingMixin):
         return queue_id

     def _get(self, queue_id):
-        return [x for x in self._proc.communicate(40)
+        return [x for x in self._proc.communicate(0.02)
                 if x['queue_id'] == queue_id]
```

Here is the patch for it.

**Comment by jsfaint** [comment] 2018-02-08 10:11
Thanks for the quick response, but it's a pity, this patch not works for me.

Patch on deoplete
```patch
diff --git a/rplugin/python3/deoplete/parent.py b/rplugin/python3/deoplete/parent.py
index 97cb510..b03ea7d 100644
--- a/rplugin/python3/deoplete/parent.py
+++ b/rplugin/python3/deoplete/parent.py
@@ -88,5 +88,5 @@ class Parent(logger.LoggingMixin):
         return queue_id

     def _get(self, queue_id):
-        return [x for x in self._proc.communicate(40)
+        return [x for x in self._proc.communicate(0.02)
                 if x['queue_id'] == queue_id]
diff --git a/rplugin/python3/deoplete/source/tag.py b/rplugin/python3/deoplete/source/tag.py
index 1dcec7f..7a32695 100644
--- a/rplugin/python3/deoplete/source/tag.py
+++ b/rplugin/python3/deoplete/source/tag.py
@@ -33,6 +33,8 @@ class Source(Base):
         self._make_cache(context)

     def gather_candidates(self, context):
+        import time
+        time.sleep(10)
         self._make_cache(context)
         candidates = []
         for c in self._cache.values():
```

Here is the new log file
[deoplete.log](https://github.com/Shougo/deoplete.nvim/files/1706542/deoplete.log)

**Comment by Shougo** [comment] 2018-02-08 10:14
It works for me.
But it does not work sometimes.
I don't know why.

**Comment by Shougo** [comment] 2018-02-09 02:24
I should use `concurrent.futures.ProcessPoolExecutor()` instead.
I will try it later.

**Comment by Shougo** [comment] 2018-02-14 03:43
I have tested `concurrent.futures.ProcessPoolExecutor()`.
It is better than before, but it cannot fix the problem completely.
It needs async io support.

https://github.com/neovim/python-client/pull/294

**Comment by Shougo** [comment] 2018-02-14 03:48
```diff
diff --git a/rplugin/python3/deoplete/deoplete.py b/rplugin/python3/deoplete/deoplete.py
index 0ce7e54..75f57fb 100644
--- a/rplugin/python3/deoplete/deoplete.py
+++ b/rplugin/python3/deoplete/deoplete.py
@@ -4,6 +4,8 @@
 # License: MIT license
 # ============================================================================
 
+from concurrent.futures import ThreadPoolExecutor
+
 from deoplete import logger
 from deoplete.parent import Parent
 from deoplete.util import (error_tb, find_rplugins)
@@ -38,8 +40,9 @@ class Deoplete(logger.LoggingMixin):
         context['rpc'] = 'deoplete_on_event'
 
         # Init processes
+        self._executor = ThreadPoolExecutor(max_workers=4)
         for n in range(0, self._max_parents):
-            self._parents.append(Parent(vim, context))
+            self._parents.append(Parent(vim, context, self._executor))
         if self._vim.vars['deoplete#_logging']:
             for parent in self._parents:
                 parent.enable_logging()
diff --git a/rplugin/python3/deoplete/parent.py b/rplugin/python3/deoplete/parent.py
index 6dba494..a97e470 100644
--- a/rplugin/python3/deoplete/parent.py
+++ b/rplugin/python3/deoplete/parent.py
@@ -13,7 +13,7 @@ from deoplete.process import Process
 
 class Parent(logger.LoggingMixin):
 
-    def __init__(self, vim, context):
+    def __init__(self, vim, context, executor):
         self.name = 'parent'
 
         self._vim = vim
@@ -21,7 +21,7 @@ class Parent(logger.LoggingMixin):
         self._child = None
         self._queue_id = ''
         self._prev_pos = []
-        self._start_process(context)
+        self._start_process(context, executor)
 
     def enable_logging(self):
         self._put('enable_logging', [])
@@ -68,14 +68,14 @@ class Parent(logger.LoggingMixin):
         if context['event'] == 'VimLeavePre':
             self._stop_process()
 
-    def _start_process(self, context):
+    def _start_process(self, context, executor):
         if self._vim.vars['deoplete#num_processes'] > 1:
             # Parallel
             python3 = self._vim.vars.get('python3_host_prog', 'python3')
             self._proc = Process(
                 [python3, context['dp_main'],
                  self._vim.vars['deoplete#_serveraddr']],
-                context, context['cwd'])
+                context, context['cwd'], executor)
         else:
             # Serial
             from deoplete.child import Child
diff --git a/rplugin/python3/deoplete/process.py b/rplugin/python3/deoplete/process.py
index 728f7fe..5bfc657 100644
--- a/rplugin/python3/deoplete/process.py
+++ b/rplugin/python3/deoplete/process.py
@@ -7,13 +7,12 @@
 import subprocess
 import os
 import msgpack
-from threading import Thread
 from queue import Queue
 from time import time, sleep
 
 
 class Process(object):
-    def __init__(self, commands, context, cwd):
+    def __init__(self, commands, context, cwd, executor):
         startupinfo = None
         if os.name == 'nt':
             startupinfo = subprocess.STARTUPINFO()
@@ -33,18 +32,16 @@ class Process(object):
             encoding='utf-8',
             unicode_errors='surrogateescape')
         self._queue_out = Queue()
-        self._thread = Thread(target=self.enqueue_output)
-        self._thread.start()
+        self._future = executor.submit(self.enqueue_output)
 
     def kill(self):
         if not self._proc:
             return
+        self._future.cancel()
         self._proc.kill()
         self._proc.wait()
         self._proc = None
         self._queue_out = None
-        self._thread.join(1.0)
-        self._thread = None
 
     def enqueue_output(self):
         while self._proc:
diff --git a/rplugin/python3/deoplete/source/tag.py b/rplugin/python3/deoplete/source/tag.py
index b407d03..88f2f9b 100644
--- a/rplugin/python3/deoplete/source/tag.py
+++ b/rplugin/python3/deoplete/source/tag.py
@@ -33,6 +33,8 @@ class Source(Base):
         self._make_cache(context)
 
     def gather_candidates(self, context):
+        import time
+        time.sleep(10)
         self._make_cache(context)
         candidates = []
         for c in self._cache.values():
```

You can test the patch.

**Comment by jsfaint** [comment] 2018-02-14 03:50
@Shougo Thanks for your effort.
I'm just curious that how did ncm handle this condition? 
Can you introduce something please? @roxma 😄

**Comment by Shougo** [comment] 2018-02-14 03:54
> I'm just curious that how did ncm handle this condition?

nvim-completion-manager uses neovim event loop instead.
deoplete does not use it.

**Comment by jsfaint** [comment] 2018-02-14 04:01
I tried the patch on windows, it doesn't work on most time.
Here is the log on windows
[deoplete.log](https://github.com/Shougo/deoplete.nvim/files/1722585/deoplete.log)

**Comment by Shougo** [comment] 2018-02-14 05:15
> It is better than before, but it cannot fix the problem completely.

**Comment by Shougo** [comment] 2018-02-15 02:22
I will test https://github.com/neovim/python-client/pull/294 and add support it later.

**Comment by Shougo** [comment] 2018-03-02 02:30
https://github.com/neovim/python-client/pull/294 is merged.
I will add the support later.

**Comment by Shougo** [comment] 2018-03-06 02:07
https://github.com/neovim/python-client/pull/294#issuecomment-369866578

I have tested it, but it does not work.

**Comment by jsfaint** [comment] 2018-03-06 02:51
@Shougo Should I test it now? or maybe later

**Comment by Shougo** [comment] 2018-03-06 03:02
I test now...
But some problems are available.

* The candidates are not displayed sometimes.  It seems similar problem with the comment.
https://github.com/Shougo/deoplete.nvim/issues/645#issuecomment-364065076

* The candidates filtering does not work.  I don't know why.  It is very confusing problem.

No magic.

**Comment by Shougo** [comment] 2018-03-06 03:46
```diff
diff --git a/rplugin/python3/deoplete/parent.py b/rplugin/python3/deoplete/parent.py
index a22b979..36fa274 100644
--- a/rplugin/python3/deoplete/parent.py
+++ b/rplugin/python3/deoplete/parent.py
@@ -5,9 +5,15 @@
 # ============================================================================
 
 import time
+import sys
+import os
+import msgpack
+import subprocess
+from functools import partial
+from queue import Queue
 
 from deoplete import logger
-from deoplete.process import Process
+from deoplete.process import Subprocess
 from deoplete.util import error_tb, error
 
 
@@ -17,10 +23,20 @@ class Parent(logger.LoggingMixin):
         self.name = 'parent'
 
         self._vim = vim
-        self._proc = None
+        self._hnd = None
+        self._stdin = None
         self._child = None
         self._queue_id = ''
         self._prev_pos = []
+        self._queue_in = Queue()
+        self._queue_out = Queue()
+        self._packer = msgpack.Packer(
+            use_bin_type=True,
+            encoding='utf-8',
+            unicode_errors='surrogateescape')
+        self._unpacker = msgpack.Unpacker(
+            encoding='utf-8',
+            unicode_errors='surrogateescape')
         self._start_process(context)
 
     def enable_logging(self):
@@ -65,48 +81,63 @@ class Parent(logger.LoggingMixin):
 
     def on_event(self, context):
         self._put('on_event', [context])
-        if context['event'] == 'VimLeavePre':
-            self._stop_process()
 
     def _start_process(self, context):
         if self._vim.vars['deoplete#num_processes'] > 1:
             # Parallel
             python3 = self._vim.vars.get('python3_host_prog', 'python3')
-            self._proc = Process(
-                [python3, context['dp_main'],
-                 self._vim.vars['deoplete#_serveraddr']],
-                context, context['cwd'])
+
+            startupinfo = None
+            if os.name == 'nt':
+                startupinfo = subprocess.STARTUPINFO()
+                startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
+            create = self._vim.loop.subprocess_exec(
+                partial(Subprocess,self),
+                python3, context['dp_main'],
+                self._vim.vars['deoplete#_serveraddr'],
+                stderr=None, cwd=context['cwd'], startupinfo=startupinfo)
+            self._hnd = self._vim.loop.create_task(create)
         else:
             # Serial
             from deoplete.child import Child
             self._child = Child(self._vim)
 
-    def _stop_process(self):
-        if self._proc:
-            self._proc.kill()
-            self._proc = None
-
     def _put(self, name, args):
+        if self._child:
+            return self._child.main(name, args, queue_id)
+
+        if not self._hnd:
+            return None
+
         queue_id = str(time.time())
+        msg = self._packer.pack({
+                'name': name, 'args': args, 'queue_id': queue_id
+            })
+        self._queue_in.put(msg)
 
-        if self._proc:
+        if self._stdin:
             try:
-                self._proc.write({
-                    'name': name, 'args': args, 'queue_id': queue_id
-                })
+                while not self._queue_in.empty():
+                    self._stdin.write(self._queue_in.get_nowait())
             except BrokenPipeError as e:
                 error_tb(self._vim, 'Crash in child process')
                 error(self._vim, 'stderr=' + str(self._proc.read_error()))
-                self._proc.kill()
-            return queue_id
-        elif self._child:
-            return self._child.main(name, args, queue_id)
-        else:
-            return None
+                self._hnd = None
+        return queue_id
 
     def _get(self, queue_id):
-        if not self._proc:
+        if not self._hnd:
             return []
 
-        return [x for x in self._proc.communicate(0.02)
-                if x['queue_id'] == queue_id]
+        outs = []
+        while not self._queue_out.empty():
+            outs.append(self._queue_out.get_nowait())
+        return [x for x in outs if x['queue_id'] == queue_id]
+
+    def _on_connection(self, transport):
+        self._stdin = transport.get_pipe_transport(0)
+
+    def _on_output(self, fd, data):
+        self._unpacker.feed(data)
+        for child_out in self._unpacker:
+            self._queue_out.put(child_out)
diff --git a/rplugin/python3/deoplete/process.py b/rplugin/python3/deoplete/process.py
index c85e3d4..e3bbcaf 100644
--- a/rplugin/python3/deoplete/process.py
+++ b/rplugin/python3/deoplete/process.py
@@ -7,6 +7,7 @@
 import subprocess
 import os
 import msgpack
+import asyncio
 from threading import Thread
 from queue import Queue
 from time import time, sleep
@@ -81,3 +82,21 @@ class Process(object):
             return
         self._proc.stdin.write(self._packer.pack(expr))
         self._proc.stdin.flush()
+
+
+class Subprocess(asyncio.SubprocessProtocol):
+    def __init__(self, plugin):
+        self.plugin = plugin
+        self.nvim = plugin._vim
+
+    def connection_made(self, transport):
+        self.nvim.async_call(self.plugin._on_connection, transport)
+        self._transport = transport
+        if isinstance(transport, asyncio.SubprocessTransport):
+            self._transport = transport.get_pipe_transport(0)
+
+    def pipe_data_received(self, fd, data):
+        self.nvim.async_call(self.plugin._on_output, fd, data)
+
+    def process_exited(self):
+        pass
```

This is the latest patch.

**Comment by Shougo** [comment] 2018-03-06 03:47
> The candidates filtering does not work. I don't know why. It is very confusing problem.

I have fixed the problem.

**Comment by Shougo** [comment] 2018-03-06 03:55
> Add a time.sleep(10) in gather_candidates() tag.py

I have tested it in asyncio patch.
It works for me.

**Comment by Shougo** [comment] 2018-03-06 05:10
https://gist.github.com/Shougo/b1292a539dcf7058c5e22b253fd46339

**Comment by jsfaint** [comment] 2018-03-06 06:27
The patch in gist was fail to apply on deoplete master
```
$ git apply asyncio.diff
error: patch fragment without header at line 284: @@ -82,7 +85,8 @@ class Deoplete(logger.LoggingMixin):
```

**Comment by Shougo** [comment] 2018-03-06 06:29
You should use `patch -p1` instead.

**Comment by jsfaint** [comment] 2018-03-06 06:52
I tried this patch on linux, it works for me.
But it looks the new version of python-neovim fail to work on Windows.
There are many errors when run `:UpdateRemotePlugins` on Windows

**Comment by Shougo** [comment] 2018-03-06 06:57
> But it looks the new version of python-neovim fail to work on Windows.
> There are many errors when run :UpdateRemotePlugins on Windows

Yes.
It is python-neovim problem.

https://github.com/neovim/python-client/pull/307

**Comment by Shougo** [comment] 2018-03-06 06:58
https://github.com/neovim/python-client/issues/306

**Comment by jsfaint** [comment] 2018-03-06 07:08
Got it, thanks!

**Comment by Shougo** [comment] 2018-03-06 07:54
You can test https://github.com/neovim/python-client/pull/307 branch.

**Comment by jsfaint** [comment] 2018-03-07 02:29
neovim-python is upgrade to 0.2.4 which fix the windows issue.
But the gist patch doesn't work on windows.
After apply the patch on deoplete, there is no completion menu show up.

I enabled debug with
```
let $NVIM_PYTHON_LOG_FILE = 'd:\nvim_log'
let $NVIM_PYTHON_LOG_LEVEL = 'DEBUG'
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'd:\deoplete.log')
```

But only got nvim_log_py3_script, there is no deoplete.log.
[nvim_log_py3_script.zip](https://github.com/Shougo/deoplete.nvim/files/1787530/nvim_log_py3_script.zip)

**Comment by Shougo** [comment] 2018-03-07 02:38
> But the gist patch doesn't work on windows.

Yes.  It is intended behavior.
Current neovim-python does not support asyncio feature in Windows.

https://github.com/neovim/python-client/releases/tag/0.2.4

**Comment by jsfaint** [comment] 2018-03-07 02:45
@Shougo Thanks for the information. 👍

**Closed** 2018-03-18 11:36 UTC
Labels: bug, performance
