### ISSUE TITLE
After 437ec07, deoplete clears single-line pasted clipboard content

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/deoplete.nvim#1090] opened 2020-03-25 11:21 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
deoplete clears single-line pasted clipboard content when popup for completion (file, around, etc) appears.

I bisected and 437ec07d0a0bac6b5bcc5ff9a345b65db955e713 is the first bad commit.

deoplete does not clear pasted contents that have MULTIPLE lines.

## Expected
deoplete does not clear pasted contents.

## Environment Information

 * deoplete version (SHA1): a76d2fbfdc4bf94dbf98d4f75a4aadb636e33784

 * OS: Debian 10.3

 * neovim/Vim `:version` output: `v0.5.0-a8f784192`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5402'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath-=~/.config/nvim
set runtimepath-=~/.config/nvim/after
set runtimepath+=/path/to/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `nvim -u vimrc`
 2. Paste clipboard content `blahblahblah` by <kbd>Shift</kbd>+<kbd>Ins</kbd>; popup for around (`[A]`) appears
 3. Again try to paste by <kbd>Shift</kbd>+<kbd>Ins</kbd>

## Screenshot (if possible)
![screenshot](https://user-images.githubusercontent.com/11627708/77530928-6e8c4f80-6ed5-11ea-98c9-cb91cc722898.gif)

asciinema cast file indicates that `blahblahblah` is removed in a few milliseconds.

**Comment by Shougo** [comment] 2020-03-25 23:29
Reproduced.  But I won't fix the problem.

Because deoplete don't guarantee clipboard feature.

You need to `set paste` before clipboard paste.

**Comment by Shougo** [comment] 2020-03-25 23:29
Or you can close the popup manually before clipboard paste.

**Closed by Shougo** 2020-03-25 23:29 UTC

**Comment by Shu-Ji** [comment] 2020-03-29 03:20
Is there a key-map for cmd+v / shift+insert to avoid this.

**Comment by Shougo** [comment] 2020-03-29 06:01
You can define it.

```vim
inoremap <C-a><expr>  (pumvisible()? "\<C-e>" : "") . "\<C-r>+"
```

Note: It is slow input, because deoplete searches completions from your pasted input.

**Comment by Shu-Ji** [comment] 2020-03-29 08:08
Many Thanks!
It seems not work on Mac OSX, maybe Vim/NVim can't capture the CTRL/CMD key.
I'll try this on my Ubuntu.

**Comment by Shougo** [comment] 2020-03-29 10:21
The terminal may overwrite the mapping.

**Comment by e-kwsm** [comment] 2020-04-01 08:50
This regression is quite inconvenient :disappointed:

**Comment by Shougo** [comment] 2020-04-01 09:18
I have decided it.

**Comment by Shougo** [comment] 2020-04-01 09:20
I should describe why I need to change it.
Because it is needed to fix candidates update problem.

**Comment by Shougo** [comment] 2020-04-01 09:21
To revert the commit means the problem will back.
It is not accepted!

And paste from clipboard is not normal input.

**Comment by e-kwsm** [comment] 2020-04-01 12:40
> And paste from clipboard is not normal input.

I'm not sure what is "normal," but I often use clipboard to paste, e.g, URI.

**Comment by Shougo** [comment] 2020-04-01 12:41
The normal means Vim's normal usage.

**Comment by Shougo** [comment] 2020-04-01 12:46
I have fixed the problem.

**Comment by e-kwsm** [comment] 2020-04-01 12:49
Now clipboard works. Thanks!
