### ISSUE TITLE
4 subprocesses by default is overkill

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#633] opened 2018-02-05 23:47 UTC
Spawning 4 subprocesses by default seems to be overkill.

It would be nice to have this more dynamic, i.e. only 1 by default, and then increase (and decrease) the number based on how busy childs are.

For starters, `g:deoplete#max_processes` could default to 2, but later this could be used as the maximum for the dynamic allocation.
A new `g:deoplete#min_processes` could be added (defaulting to 1).

Keep in mind that there are users (like me) who spawn Vim very often.
I have deoplete being lazily loaded on InsertEnter, but the recommended installation is to just enable it on startup, which includes usage for `git commit` etc.

**Comment by Shougo** [comment] 2018-02-06 00:12
4 subprocesses may be overkill.
But I don't want to change it to 1.

2 may be better.

> It would be nice to have this more dynamic, i.e. only 1 by default, and then increase (and decrease) the number based on how busy childs are.

If you can implement the feature, PR is welcome.

**Comment by balta2ar** [comment] 2018-02-06 08:18
> It would be nice to have this more dynamic, i.e. only 1 by default, and then increase (and decrease) the number based on how busy childs are.

Frankly, to me it sounds overcomplicated. deoplete with Sources is not some highload system with varying load to have a shrinking and growing pool of workers. Sources are fixed. I think finding a reasonable number of workers that works best for your configuration plus lazyloading is not a bad tradeoff to avoid overengineering in deoplete.

**Comment by magicalbanana** [comment] 2018-02-06 14:48
I am getting crazy CPU consumptions. Not sure if this is from deoplete but it's really crazy.

![image](https://user-images.githubusercontent.com/7953984/35865551-70de899a-0b1a-11e8-8b41-166195a10837.png)

**Comment by Shougo** [comment] 2018-02-06 23:31
Unfortunately, I cannot reproduce the problem.
You can investigate more.

**Comment by kiooss** [comment] 2018-02-07 01:07
@magicalbanana Are you using Vim8 with nvim-yarp? I got the same issue and the python processes remain even vim is closed. Neovim has no problem.

**Comment by Shougo** [comment] 2018-02-07 01:37
@kiooss 

I think you can fix it by the patch.

https://github.com/Shougo/deoplete.nvim/issues/637#issuecomment-363606021

**Comment by Shougo** [comment] 2018-02-07 01:38
I will add the serial process support.
Closing.

**Closed by Shougo** 2018-02-07 01:38 UTC

**Comment by blueyed** [comment] 2018-02-07 16:24
> I will add the serial process support.
> Closing.

Can we change the default to 2 for now?

> I think finding a reasonable number of workers that works best for your configuration plus lazyloading is not a bad tradeoff to avoid overengineering in deoplete.

OK.
1. However, I got the idea of making it dynamic based on the var name (`g:deoplete#max_processes`) likely.  It should be `g:deoplete#num_processes` or similar in case it is fixed.
2. lazyloading is not being done by default, and needs some special stuff with vim-plug etc, i.e. almost nobody is using it.

**Comment by balta2ar** [comment] 2018-02-07 17:02
> It should be `g:deoplete#num_processes` or similar in case it is fixed

Makes sense.

By the way, what are your CPU-intensive deoplete Sources that you wanted to dynamically distribute over processes?

Speaking of distribution: I'm not sure about the exact current implementation, but can it happen that two heavy CPU consumers are put into the same process which will effectively make them linear (unless they implement `is_async`)? Could this be a problem?  For such cases it could be helpful to have a command that would print current distribution.

**Comment by Shougo** [comment] 2018-02-07 23:59
> For such cases it could be helpful to have a command that would print current distribution.

I think it should be printed in debug log.

**Comment by Shougo** [comment] 2018-02-08 00:01
> It should be g:deoplete#num_processes or similar in case it is fixed

I have renamed it.

**Comment by Shougo** [comment] 2018-02-08 00:20
I have improved the logging.

**Comment by blueyed** [comment] 2018-02-08 19:16
@Shougo 
> I have improved the logging.

Could not see it in 3dee4b1...c145a7f ?!

**Comment by Shougo** [comment] 2018-02-08 23:07
Sorry, I have forgot to push it.
I have pushed.
