### ISSUE TITLE
It will be complemented automatically.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#1141] opened 2020-10-27 15:09 UTC
# Problems summary
It will be complemented automatically.

## Expected
It should not be complemented automatically.

## Environment Information

 * deoplete version (SHA1): c09da81e9824fc113323573abea3a2ec13c04409

 * OS: Mac

 * neovim/Vim `:version` output: NVIM v0.5.0-nightly-261-g75996a2cd

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call deoplete#custom#option('keyword_patterns', {	
    \ 'denite-filter': '',	
    \})	
call deoplete#custom#option({
    \ 'min_pattern_length': 1,
    \})
call deoplete#custom#option('sources', {
    \ 'css': ['buffer', 'lsp'],
    \ 'html': ['buffer', 'file', 'lsp'],
    \ 'graphql': ['buffer'],
    \ 'javascript': ['buffer', 'lsp'],
    \ 'javascript.jsx': ['buffer', 'lsp'],
    \ 'scala': ['buffer', 'lsp'],
    \ 'typescript': ['buffer', 'lsp'],
    \ 'typescript.tsx': ['buffer', 'lsp'],
    \ 'rust': ['buffer', 'lsp'],
    \ 'python': ['buffer', 'lsp'],
    \})
call deoplete#custom#source('_', 'converters', [
    \ 'converter_remove_paren',
    \ 'converter_remove_overlap',
    \ 'converter_truncate_abbr',
    \ 'converter_truncate_info',
    \ 'converter_truncate_menu',
    \ 'converter_auto_delimiter',
    \])
call deoplete#custom#source('_',
    \ 'matchers', ['matcher_fuzzy', 'matcher_length'])
call deoplete#custom#source('lsp', 'converters', ['converter_reorder_attr'])
call deoplete#custom#filter('converter_reorder_attr', 'attrs_order', {
    \ 'rust': { 'kind': ['!Snippet'] }
    \})
call deoplete#custom#source('LanguageClient', 'converters', ['converter_reorder_attr'])
call deoplete#custom#filter('converter_reorder_attr', 'attrs_order', {
    \ 'haxe': { 'kind': ['!Snippet'] }
    \})
call deoplete#custom#source('lsp', 'dup', v:false)
call deoplete#custom#source('LC', 'dup', v:false)

inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"
inoremap <expr><C-e> deoplete#cancel_popup()

call deoplete#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. touch foo.js
 2. nvim foo.js
 3. Enter the following
```
aaa.bbb(``)
```
 4. Enters insert mode between **``**.
 5. Repeat until symptoms occur.

## Screenshot (if possible)
![issue](https://user-images.githubusercontent.com/3197942/97320916-a74c3700-18b1-11eb-8e41-cff2c34086b2.gif)

**Comment by Shougo** [comment] 2020-10-27 23:25
@nabezokodaikon Please provide the minimal vimrc!  It is not minimal.

**Comment by Shougo** [comment] 2020-10-27 23:27
You both use LanguageClient-neovim and deoplete-lsp.  Why?
I don't recommend for you to use LanguageClient-neovim source. It uses old interface.

Please read the issue.
https://github.com/Shougo/deoplete.nvim/issues/1013

**Comment by Shougo** [comment] 2020-10-27 23:28
I will close the issue.  Because you have not upload the minimal vimrc and I cannot reproduce the problem.

**Comment by nabezokodaikon** [comment] 2020-10-28 10:53
Thank you for your reply.
LanguageClient-neovim is loaded only in Haxe.
I will investigate again.

**Comment by nabezokodaikon** [comment] 2020-10-28 11:08
For the time being, I will post a large screenshot.

<img width="559" alt="スクリーンショット 2020-10-28 20 07 24" src="https://user-images.githubusercontent.com/3197942/97428464-5c85fa00-1959-11eb-8e69-9ca86d8ea6fe.png">

**Comment by Shougo** [comment] 2020-10-28 11:13
OK

**Comment by nabezokodaikon** [comment] 2020-10-28 11:52
Other vimrc.

dein.toml
```toml
[[plugins]]
repo = 'neovim/nvim-lspconfig'
```

Read nvim-lspconfig
```vimrc
luafile ~/.config/nvim/lua/nvim-lspconfig.lua
```

nvim-lspconfig.lua
```lua
local lsp = require'nvim_lsp'
lsp.tsserver.setup {}
```

**Comment by nabezokodaikon** [comment] 2020-10-28 11:55
It ’s a problem from another point of view.
`` `lua
local lsp = require'nvim_lsp'
lsp.tsserver.setup {}
`` ```
If you remove, the buffer candidates will disappear even though you have set the buffer in deoplete.

**Comment by Shougo** [comment] 2020-10-28 11:58
Please merge the configuration to one file.
I cannot reproduce it.

**Closed** 2020-10-28 13:27 UTC
Labels: needs reproduction instructions, source problem

**Comment by Shougo** [comment] 2020-10-28 13:32
@nabezokodaikon Please test the latest version.

**Comment by nabezokodaikon** [comment] 2020-10-28 13:42
I tested it several times but it didn't happen.

**Comment by nabezokodaikon** [comment] 2020-10-28 13:45
I tried gradually from the smallest configuration, but couldn't figure out how to reproduce it.
I apologize to you for a fuss over.
I will be careful from the next time.

**Comment by Shougo** [comment] 2020-10-28 13:50
OK.
