### ISSUE TITLE
Constant CPU usage

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#336] opened 2016-09-02 18:17 UTC
I am seeing constant CPU usage for idle Vim processes.

The following processes (PID 7717) uses ~3% CPU constantly.

Output from `pstree -apl`:

```
  |   |   `-nvim,7699 …/usr/bin/postgres-log
  |   |       |-python3,7717 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() /home/user/.vim/neobundles/deoplete/rplugin/python3/deoplete
  |   |       |   |-python,7718 -u /home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py --desc-length 0 --docstrings
  |   |       |   |-python,7760 -u /home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py --desc-length 0 --docstrings
  |   |       |   |-python,7984 -u /home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py --desc-length 0 --docstrings
  |   |       |   |-{python3},7721
  |   |       |   |-{python3},7722
  |   |       |   |-{python3},7763
  |   |       |   |-{python3},7764
  |   |       |   |-{python3},7991
  |   |       |   `-{python3},7992
  |   |       `-{nvim},7703
```

`strace -f -p 7717` gives:

```
strace: Process 7717 attached with 7 threads
[pid  7992] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid  7991] select(0, NULL, NULL, NULL, {0, 613} <unfinished ...>
[pid  7764] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid  7763] select(0, NULL, NULL, NULL, {0, 688} <unfinished ...>
[pid  7722] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid  7721] select(0, NULL, NULL, NULL, {0, 2742} <unfinished ...>
[pid  7717] epoll_wait(4,  <unfinished ...>
[pid  7991] <... select resumed> )      = 0 (Timeout)
[pid  7991] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7763] <... select resumed> )      = 0 (Timeout)
[pid  7763] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7722] <... restart_syscall resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid  7722] futex(0x7fd180001570, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1472839298, 253294000}, ffffffff <unfinished ...>
[pid  7992] <... restart_syscall resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid  7992] futex(0x7fd174001570, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1472839298, 253373000}, ffffffff <unfinished ...>
[pid  7721] <... select resumed> )      = 0 (Timeout)
[pid  7721] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7764] <... restart_syscall resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid  7764] futex(0x7fd178001570, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1472839298, 258198000}, ffffffff <unfinished ...>
[pid  7991] <... select resumed> )      = 0 (Timeout)
[pid  7763] <... select resumed> )      = 0 (Timeout)
[pid  7991] futex(0x7fd1946b6764, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 23656981, {1472839298, 256670000}, ffffffff <unfinished ...>
[pid  7763] futex(0x7fd1946b6764, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fd1946b6760, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1} <unfinished ...>
[pid  7991] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  7763] <... futex resumed> )       = 0
[pid  7763] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7991] futex(0x7fd1946b6720, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  7991] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7722] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  7722] futex(0x7fd180001570, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1472839298, 263421000}, ffffffff <unfinished ...>
[pid  7992] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  7992] futex(0x7fd174001570, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1472839298, 263474000}, ffffffff <unfinished ...>
[pid  7721] <... select resumed> )      = 0 (Timeout)
[pid  7721] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7764] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  7764] futex(0x7fd178001570, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1472839298, 268408000}, ffffffff <unfinished ...>
[pid  7763] <... select resumed> )      = 0 (Timeout)
[pid  7991] <... select resumed> )      = 0 (Timeout)
[pid  7991] futex(0x7fd1946b6764, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 23656983, {1472839298, 266896000}, ffffffff <unfinished ...>
[pid  7763] futex(0x7fd1946b6764, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fd1946b6760, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1} <unfinished ...>
[pid  7991] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  7763] <... futex resumed> )       = 0
[pid  7763] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7991] futex(0x7fd1946b6720, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  7991] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  7722] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  7992] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  7992] futex(0x7fd1946b6764, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 23656985, {1472839298, 268540000}, ffffffff <unfinished ...>
[pid  7722] futex(0x7fd1946b6764, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fd1946b6760, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
```

It generates 5290 lines in 2 seconds!

It has used nearly ~1hr of CPU already (during a few days).

It has only one file opened in there, with `&ft=sh`.

Therefore it is suspicious to have 3 `deoplete_jedi/server.py` processes there, but those have not used any CPU.

I could not make `ps` show me CPU time spent on threads - is that possible?

This is not unusual: I have ~30 such processes, ranging from 1-3% of CPU usage!

How can I debug this further?

Neovim master (v0.1.6-36-g0ade1bb).
Deoplete f387452.

**Comment by Shougo** [comment] 2016-09-02 23:50
It seems deoplete-jedi problem.  Please create the issue for it.
deoplete does not create the threads.
Closing.

Note:
You should create minimal init.vim and upload the reproduce ways.

**Closed by Shougo** 2016-09-02 23:50 UTC

**Comment by blueyed** [comment] 2016-09-03 00:00
Common, how should I create a minimal vimrc for that?!

The CPU usage is on `python3,7717 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() /home/user/.vim/neobundles/deoplete/rplugin/python3/deoplete` - the deoplete-jedi processes have no CPU usage.
Regarding the threads: I said that I could not look at their usage, and if you know a way to do it - but they are probably also at 0 (since the processes are).

**Comment by Shougo** [comment] 2016-09-03 00:04
> Common, how should I create a minimal vimrc for that?!

Why does not you test it with minimal vimrc?
I cannot reproduce the problem!
For example, you can test it without deoplete-jedi.

**Comment by blueyed** [comment] 2016-09-03 00:05
It seems to take hours/days to happen, so it is not easy ro reproduce.

But a fair point: I can investigate in that area.

I just notice it after a while, e.g. when looking at `htop` because of something else.

**Comment by blueyed** [comment] 2016-09-03 00:07
@zshee
Any idea?

After all, all the `strace` output seems to come from the threads.

**Comment by Shougo** [comment] 2016-09-03 00:07
> It seems to take hours/days to happen, so it is not easy ro reproduce.

OK. Please describe it at first.
I have not ESP skill.

**Comment by blueyed** [comment] 2016-09-03 00:11
@Shougo 
I think I've described it all: I've noticed that some processes keep on eating CPU for no reason, which seems to be related to threads constantly polling.  In the case at hand, the Neovim instance was running in some tmux window since a few days (with suspend-to-RAM inbetween), and only a text file was opened there).

I think that you are right about deoplete-jedi causing it, so we should take it there - but this issue here has info already, so let's wait for @zchee.

**Comment by Shougo** [comment] 2016-09-03 00:12
I have added remote pdb support for it.

**Comment by rafi** [comment] 2016-09-18 17:17
Experiencing this too. https://github.com/zchee/deoplete-jedi/issues/59

**Comment by blueyed** [comment] 2016-09-21 08:05
See https://github.com/zchee/deoplete-jedi/issues/61.

@rafi 
Are you also seeing constant CPU usage, or just that deoplete-jedi is loaded when it should not be.
Please see https://github.com/zchee/deoplete-jedi/issues/61, and try the `strace` from there, and look at the output file using `tail -f`.

**Comment by Shougo** [comment] 2016-09-22 05:42
It is fixed in the latest deoplete.
