### ISSUE TITLE
Up/Down arrows do not move selection

### ISSUE THREAD

**Issue by kthibodeaux** [Shougo/deoplete.nvim#1026] opened 2019-10-04 22:07 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
When autocompleting the up and down arrows do not work if the filetype is not `text` or (null).  Pressing either flashes a selection, but does not act like `Ctrl + n` nor `Ctrl + p`.

## Expected
Up and down are expected to act like `Ctrl + n` nor `Ctrl + p`.

## Environment Information

 * deoplete version (SHA1):
i did a bisect on deoplete and found:
WORKING: `98566131d5f574ee2896138bdda08afa68bda416`
FIRST BROKEN: `782fdaf0671d3acc0d70920ed7ca521cfdd5578e`

 * OS: linux (manjaro)

 * neovim/Vim `:version` output: 
```
:version
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstric
t-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -D
NVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim
/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
i have no idea, i tried to find the minimal, but even binary searching no single thing seems to indicate what the minimum vimrc is (i know this will likely get closed because of this, but i have found the exact commit that causes the issue, so i hope that can make up for it)

my config can be found here: https://github.com/kthibodeaux/.dotfiles/blob/master/neovim/.config/nvim/init.vim

## How to reproduce the problem from neovim/Vim startup (Required!)

https://asciinema.org/a/dfkyDaTb81y1eJJRGGrD8hMXi

**Comment by Shougo** [comment] 2019-10-06 10:37
You have not uploaded minimal vimrc and real reproduce instructions.
So I will close the issue.

Please read the issue template and other issues.

**Comment by Shougo** [comment] 2019-10-06 10:38
```vim
set rtp+=~/work/deoplete.nvim/

let g:deoplete#enable_at_startup = 1
```

I have tested above vimrc.
Please upload the instructions.

**Comment by Shougo** [comment] 2019-10-06 10:39
If you or other people upload the instructions, I will reopen the issue.
If not, I will ignore your report.

**Comment by Shougo** [comment] 2019-10-06 10:42
> (i know this will likely get closed because of this, but i have found the exact commit that causes the issue, so i hope that can make up for it

The breaking commit is OK.
But the issue `must` be reproduce-able for me.
Because, if I fix the issue, I cannot check that it is real fix.

Note: Revert commit is not the real fix.

**Comment by Shougo** [comment] 2019-10-06 10:49
I have tested deoplete-ruby in the screenshot, but I cannot reproduce the problem.

https://github.com/fishbullet/deoplete-ruby

**Comment by Shougo** [comment] 2019-10-06 10:50
@kthibodeaux Your vimrc is too huge.

https://github.com/kthibodeaux/.dotfiles/blob/master/neovim/.config/nvim/init.vim

Please reduce it like my minimal vimrc.

**Comment by kthibodeaux** [comment] 2019-10-06 11:28
@Shougo i have managed to come up with a minimal vimrc, but it turns out it might not be an issue with deoplete at all. it seems ale and deoplete together make this an issue

```
" Plugins {{{
call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'w0rp/ale'
call plug#end()
" }}}

let g:deoplete#enable_at_startup = 1
```

**Comment by kthibodeaux** [comment] 2019-10-06 11:35
I found the fix!

For anyone else looking, this is from the ale readme:

```
" Enable completion where available.
" This setting must be set before ALE is loaded.
"
" You should not turn this setting on if you wish to use ALE as a completion
" source for other completion plugins, like Deoplete.
let g:ale_completion_enabled = 1
```

But it seems that might be enabled by default anyway, so before loading the plugin add this to vimrc:

```
let g:ale_completion_enabled = 0
```

**Comment by kthibodeaux** [comment] 2019-10-06 11:39
If I add this before I load plugins in my init.vim, it works.  But, this does not fix minimal init.vim.

`let g:ale_completion_enabled = 0`

**Comment by Shougo** [comment] 2019-10-06 14:58
OK.  I will test it later.

**Comment by Shougo** [comment] 2019-10-07 12:59
Reproduced.  It is regression of deoplete.

Thanks.

**Closed** 2019-10-07 12:59 UTC
Labels: cannot reproduce, needs reproduction instructions
