### ISSUE TITLE
Throws a lot of errors when editing `go` files.

### ISSUE THREAD

**Issue by magicalbanana** [Shougo/deoplete.nvim#546] opened 2017-09-21 17:46 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I keep getting errors when editing `go` files (I have more issues, but let's focus on this one for now).

## Expected
To be there there is no error and that it is smooth? Because it lags a lot.

## Environment Information

 * deoplete version(SHA1):

 * OS:
 macOS Sierra 10.12.6

 * neovim version:
NVIM v0.2.0
 * `:CheckHealth` result(neovim ver.0.1.5-452+):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 10ms
  - INFO: $TERM: xterm-256color
  - INFO: default-terminal: screen-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - SUGGESTIONS:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
if has('nvim') == 1
  inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

  let g:deoplete#enable_at_startup = 1

  " deoplete-go
  let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
  let g:deoplete#sources#go#use_cache = 1
endif
```

## The reproduce ways from neovim starting (Required!)

 1. start up nvim
 2. open a `go` file
 3. edit away

## Generate a logfile if appropriate
`:messages`
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/kgan/src/github.com/meinekonfig/meinekonfig/config/vim/bundle/complete/deoplete/rplugin/python3/deoplete/deoplet
e.py", line 89, in gather_results
[deoplete]     charpos = source.get_complete_position(ctx)
[deoplete]   File "/Users/kgan/.config/nvim/bundle/complete/deoplete/./rplugin/python3/deoplete/source/omni.py", line 36, in get_complete_
position
[deoplete]     pos = self._get_complete_position(context, current_ft, filetype)
[deoplete]   File "/Users/kgan/.config/nvim/bundle/complete/deoplete/./rplugin/python3/deoplete/source/omni.py", line 51, in _get_complete
_position
[deoplete]     'deoplete#util#exists_omnifunc', omnifunc):
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Keyboard interrupt'
[deoplete] Could not get completions from: omni.  Use :messages for error details.
```

**Comment by Shougo** [comment] 2017-09-22 01:43
You have interrupted the omnifunc.
Have you installed omnifunc?

We have not ESP skills.
Please provide the correct minimal vimrc.

**Comment by Shougo** [comment] 2017-09-22 01:45
I cannot reproduce the problem.

Question:

* What is the go file?  It is just empty file?
* You can reproduce it using the init.vim?  Really?

I will close it if you cannot provide the go file and the minimal init.vim.

**Comment by magicalbanana** [comment] 2017-09-25 23:56
Hi @Shougo, so I have my own vim config, https://github.com/meinekonfig/vim/tree/bundle.

How do I install omnifunc?

**Comment by Shougo** [comment] 2017-09-26 00:05
This is not the minimal vimrc.
Please read other issues.

**Comment by Shougo** [comment] 2017-09-26 00:06
You should test it with the minimal vimrc.

**Comment by Shougo** [comment] 2017-09-26 00:10
This is the minimal vimrc.

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/deoplete-go/

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
let g:deoplete#sources#go#use_cache = 1
```

I will close the issue if you cannot test it with the minimal vimrc.

**Comment by magicalbanana** [comment] 2017-09-27 16:40
I have done this and it does not return errors however, it causes sluggishness. 

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    3  62.908872   0.005882  deoplete#util#exists_omnifunc()
    1  62.902198   0.000618  go#complete#Complete()
    1  62.901580   0.000323  <SNR>445_gocodeAutocomplete()
    5  62.894219  62.894022  go#util#System()
    1  62.707414   0.000210  <SNR>445_gocodeCommand()
    5  14.535886   0.001115  gitgutter#all()
    5  14.534693   0.001272  gitgutter#process_buffer()
    5  14.531968   0.016622  gitgutter#diff#run_diff()
    2  14.497366   0.000155  gitgutter#utility#file_relative_to_repo_root()
    1  14.497069  14.496977  gitgutter#utility#system()
    1   1.836195   0.000112  go#util#env()
    1   1.836080   0.000047  go#util#goroot()
  822   0.529666   0.018199  airline#extensions#branch#get_head()
  822   0.511467   0.020434  airline#extensions#branch#head()
  822   0.375510   0.127003  <SNR>283_update_branch()
  822   0.212831   0.039856  <SNR>283_update_git_branch()
    1   0.189107   0.000158  <SNR>445_gocodeEnableOptions()
  822   0.174710   0.090228  airline#check_mode()
  822   0.172975   0.013654  fugitive#head()
  822   0.134483   0.072282  airline#extensions#hunks#get_hunks()
```

**Comment by Shougo** [comment] 2017-09-28 02:11
It is just vim-go issue.
`go#util#System()` is vim-go function.

**Comment by romeovs** [comment] 2017-09-28 11:27
Has an issue been made in`vim-go`? If so, maybe we should link it here so people can track progress.

**Comment by magicalbanana** [comment] 2017-09-28 13:57
@romeovs yeah, here's the issue, https://github.com/fatih/vim-go/issues/1482

**Comment by Shougo** [comment] 2017-09-29 01:57
I will check the issue.

**Comment by Shougo** [comment] 2017-09-29 02:07
@magicalbanana @romeovs I think you should disable gocode omnifunc.

**Comment by Shougo** [comment] 2017-09-29 02:07
Ah, I get it.
I should improve the behavior.

**Comment by Shougo** [comment] 2017-09-29 02:08
gocode omnifunc is slow.  It is vim-go problem.
But deoplete should improve the behavior.

**Comment by magicalbanana** [comment] 2017-09-30 15:55
@Shougo I can't be 100% yet, but doing what you suggested (`setlocal omnifunc=`) seems to be working.

**Comment by Shougo** [comment] 2017-10-01 12:59
Fixed.

**Closed** 2017-10-01 12:59 UTC
Labels: performance
