### ISSUE TITLE
commit 9c2bf12 makes deoplete to autosolect option

### ISSUE THREAD

**Issue by dbarrosop** [Shougo/deoplete.nvim#917] opened 2019-01-14 13:01 UTC
Hello,
looks like commit 9c2bf125c6be6f5dd9edabbfcc53aa1bace3c610 causes deoplete to autoselect and insert the first option make it unusable. Reverting to commit a2019e9 fixes the issue. My configuration is:

```
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option({
	\ 'auto_refresh_delay': 30,
	\ 'auto_complete_delay': 30,
	\ 'smart_case': v:true,
	\ 'camel_case': v:true,
	\ 'delimiters': ['/', '.'],
\ })
set completeopt='menu'
```

Thanks!
David

**Comment by Shougo** [comment] 2019-01-14 13:10
I have tested your configuration and it works.

It must be:

```vim
set completeopt=menu
```

**Comment by Shougo** [comment] 2019-01-14 13:11
Closing.  It works for me.

You have not upload the minimal init.vim and the reproduce instructions

**Closed** 2019-01-14 13:11 UTC

**Comment by cristobaltapia** [comment] 2019-01-15 08:32
I am having this problem too. It is very strange: in python, if I type `print(` (relative fast) then it gets automatically replaced by a different word that was matched, in a specific case e.g. it gets replaced by a function I have with the name `project_shape_into_plane)` (note the closing "`)`"). 
Reverting to commit a2019e9f4f764a48a96a75e96b1b4f0bb79b4827 does work for too.

**Comment by dbarrosop** [comment] 2019-01-15 09:56
@Shougo do you have a docker container or something we can use to help you reproduce the problem? Would be nice to have some environment you control where we put the `init.vim` that reproduces the problem

**Comment by ndevvy** [comment] 2019-01-16 20:57
i've also had this issue in python buffers recently.  i just tried the latest version of deoplete and it persisted, but then i found that removing and re-installing the [deoplete-jedi](https://github.com/zchee/deoplete-jedi) plugin seems to have fixed it for me?  i'm unclear why that would be the case, just happy i don't have to ditch deoplete in py

**Comment by Shougo** [comment] 2019-01-17 00:05
@ndevvy Please change `prev_completion_mode` option value.
For configure, please read the documentation.

**Comment by Shougo** [comment] 2019-01-17 00:10
And please upload the minimal vimrc and the reproduce instructions.
It must be reproduce-able for me.

**Comment by Shougo** [comment] 2019-01-17 00:19
I have updated deoplete.  Please test it.

**Comment by cristobaltapia** [comment] 2019-01-17 07:50
I have updated deoplete and it seems that the problem is gone now. Thanks!

**Comment by dbarrosop** [comment] 2019-01-17 08:09
I tested as well and current master works great for me. Thanks a lot @Shougo.

I understand that replicating issues is hard, may I insist on my previous suggestion of having an official `Dockerfile` in this repo to make with a controlled version of nvim, the python and other components already preinstalled and maybe a plugin manager to try to make it easier?

**Comment by Shougo** [comment] 2019-01-17 08:35
It is trival fix.

I have reproduced the problem and I get the reason..
I will fix it completely later.
Please wait.

**Comment by Shougo** [comment] 2019-01-17 15:32
I have fixed it completely.
Please use the latest version.
