### ISSUE TITLE
Exception during buffer.on_event

### ISSUE THREAD

**Issue by Mte90** [Shougo/deoplete.nvim#672] opened 2018-02-27 14:12 UTC
# Problems summary
On first run of neovim I get this error. i am not sure if it is a plugin conflict but the code refer only to deoplete.

## Expected
No error

## Environment Information

 * deoplete version(SHA1): last commit

 * OS:linux

 * neovim/Vim version:neovim 0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

https://github.com/Mte90/My-Scripts/blob/master/vim/vimrc

## The reproduce ways from neovim/Vim starting (Required!)

 1. Run neovim

## Screen shot (if possible)

![screenshot_20180227_150955](https://user-images.githubusercontent.com/403283/36733335-94243e92-1bd0-11e8-9b6f-29647b076fb1.png)

**Comment by Shougo** [comment] 2018-02-28 00:14
Sorry.  I cannot reproduce the error.
And the vimrc is not minimal.

Closing.

**Closed** 2018-03-06 05:34 UTC
Labels: cannot reproduce
