### ISSUE TITLE
Breaks single-repeat

### ISSUE THREAD

**Issue by nyarly** [Shougo/deoplete.nvim#282] opened 2016-06-02 17:01 UTC
# Problems summary

Deoplete (and neocomplete) seems to hijack input somehow such that it breaks single-repeat. (i.e. `.`)

For instance, consider:

With the cursor on `WrongFunction` I `ciwSom` and deoplete suggests `SomeFunction`, which I accept.
I go to another occurrence of `WrongFunction`, and hit `.`, expecting it also to be replaced with `SomeFunction` - most of the time, the result is that it's replaced with _something_, but (at a guess) it's replaced with whatever came up as the first suggestion by deoplete.

## Expected

I want my edits that include a deoplete suggestion to be repeatable.

## Environment Information

 * OS: OS X and Linux

 * nvim-python-doctor result:
https://github.com/tweekmonster/nvim-python-doctor

```
Include the output below this line in your Github issues.


\e[1;37m## Neovim Python Diagnostic\e[m

- Neovim Version: \e[36mNVIM 0.1.4\e[m

\e[1;37m## Remote plugins\e[m

**Manifest File**: `/Users/jlester/.config/nvim/.init.vim-rplugin~`
**Plugin**: /Users/jlester/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete
  - Registered: \e[32mYes\e[m
\e[36m**Manifest is up to date**\e[m

\e[1;37m### 'python' info from /usr/local/bin/nvim\e[m

\e[33mWARN: 'g:python_host_prog' is not set.\e[m
\e[33mWARN: Fallback to '/usr/local/bin/python'\e[m
**Python Version**: `2.7.11`
**Neovim Package Version**: `neovim (0.1.8)`\e[33m (latest: ``)\e[m

\e[1;37m### 'python3' info from /usr/local/bin/nvim\e[m

\e[33mWARN: 'g:python3_host_prog' is not set.\e[m
\e[33mWARN: Fallback to '/usr/local/bin/python3'\e[m
**Python Version**: `3.5.1`
**Neovim Package Version**: `neovim (0.1.8)`\e[33m (latest: ``)\e[m

\e[1;37m## Python versions visible in the current shell\e[m

- **python** version: `Python 2.7.11`
  - **path**: `/usr/local/bin/python`
  - **neovim** version: `neovim (0.1.8)`
- **python3** version: `Python 3.5.1`
  - **path**: `/usr/local/bin/python3`
  - **neovim** version: `neovim (0.1.8)`

\e[1;37m## Messages or Suggestions\e[m

- FIX: Upgrade the neovim package with: `pip2 install -U --user neovim`.
- FIX: Upgrade the neovim package with: `pip3 install -U --user neovim`.
```

But:
```
⮀ pip2 install -U --user neovim
Requirement already up-to-date: neovim in /Users/jlester/Library/Python/2.7/lib/python/site-packages
Requirement already up-to-date: greenlet in /Users/jlester/Library/Python/2.7/lib/python/site-packages (from neovim)
Requirement already up-to-date: trollius in /Users/jlester/Library/Python/2.7/lib/python/site-packages (from neovim)
Requirement already up-to-date: msgpack-python>=0.4.0 in /Users/jlester/Library/Python/2.7/lib/python/site-packages (from neovim)
Requirement already up-to-date: six in /Users/jlester/Library/Python/2.7/lib/python/site-packages (from trollius->neovim)
Requirement already up-to-date: futures in /Users/jlester/Library/Python/2.7/lib/python/site-packages (from trollius->neovim)
⮀ pip3 install -U --user neovim
Requirement already up-to-date: neovim in /usr/local/lib/python3.5/site-packages
Requirement already up-to-date: greenlet in /usr/local/lib/python3.5/site-packages (from neovim)
Requirement already up-to-date: msgpack-python>=0.4.0 in /usr/local/lib/python3.5/site-packages (from neovim)
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

**Comment by Shougo** [comment] 2016-06-02 23:09
I think it is Vim/neovim bug.
So it should be fixed.  But you must create the reproduce ways from neovim starting.
Please see other issues.

> I go to another occurrence of WrongFunction, and hit ., expecting it also to be replaced with SomeFunction - most of the time, the result is that it's replaced with something, but (at a guess) it's replaced with whatever came up as the first suggestion by deoplete.

I cannot reproduce the problem using the description.

**Comment by Shougo** [comment] 2016-06-18 00:22
This is the real reproduce ways.

https://github.com/vim/vim/issues/874

**Comment by Shougo** [comment] 2016-07-23 02:29
It is fixed in https://github.com/neovim/neovim/pull/5105

**Closed** 2016-08-18 22:28 UTC
Labels: reproduce ways
