### ISSUE TITLE
Way too many suggestions

### ISSUE THREAD

**Issue by lee-kagiso** [Shougo/deoplete.nvim#120] opened 2016-01-11 08:31 UTC
I uninstalled YCM and installed Deoplete, and it is super fast!
However I am getting far too many irrelevant suggestions.

Eg, in python I type `import` and I get about `50` suggestions instead of 1:

![deoplete](https://cloud.githubusercontent.com/assets/11830393/12229259/7d8eb3ac-b84e-11e5-91ef-f3e2173bdd43.png)

**Comment by wsdjeg** [comment] 2016-01-11 08:35
`[T]`means tags source

**Comment by lee-kagiso** [comment] 2016-01-11 08:51
OK, so I tried to turn off tag sources like this: https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L778

```
let g:deoplete#ignore_sources = ['tag'] 
```

But I get this error then:

```
core/models.py                                                                                                                                                                                                              1,1            Top
Error detected while processing function deoplete#init#enable..deoplete#init#_variables..deoplete#util#set_default:                                                                                                                           
line    4:                                                                                                                                                                                                                                    
E706: Variable type mismatch for: g:deoplete#ignore_sources
```

**Comment by wsdjeg** [comment] 2016-01-11 08:57
you should put this after neobunld end or use neobundle hooks

**Comment by wsdjeg** [comment] 2016-01-11 08:58
type mismatch means you difinded a diff type var

**Comment by lee-kagiso** [comment] 2016-01-11 08:58
I am using vim-plug and it is after ```call plug#end()```

**Comment by wsdjeg** [comment] 2016-01-11 09:00
ok I wilk fond what is going on ,now i am on the bus,and i will do it tonight ,sorry for take your time

**Comment by lee-kagiso** [comment] 2016-01-11 09:04
I think I am taking your time with my issue :)

**Comment by wsdjeg** [comment] 2016-01-11 09:05
g:deoplete#ignore_sources default value is {},can you try with  
let g:deoplete#ignore_sources ={'tag'}

**Comment by lee-kagiso** [comment] 2016-01-11 09:06
I get this:

```
E121: Undefined variable: tag
E15: Invalid expression: {'tag'}
```

**Comment by wsdjeg** [comment] 2016-01-11 09:07
sorry
I means 
let g:deoplete#ignore_sources ={'_'：'tag'}

**Comment by wsdjeg** [comment] 2016-01-11 09:09
if it works I think you can change to
let g:deoplete#ignore_sources ={'python'：'tag'}

**Comment by wsdjeg** [comment] 2016-01-11 09:10
and doc says 
g:deoplete#ignore_sources

**Comment by lee-kagiso** [comment] 2016-01-11 09:17
Tags still appear, I guess #116

**Comment by wsdjeg** [comment] 2016-01-11 10:24
I think this should work,but it does not ,@Shougo can you help us?
```vim
            let g:deoplete#ignore_sources = get(g:,'deoplete#ignore_sources',{})
            let g:deoplete#ignore_sources.java = ['tag']

```

**Comment by wsdjeg** [comment] 2016-01-11 10:33
I test by this step;
 open java file by neovim 
`let b:deoplete_ignore_sources = ['omni','buffer','tag']`
then the `[B]` is ignored but tag and omni still appear

**Comment by tony** [comment] 2016-01-11 14:08
Duplicate of #116

**Comment by wsdjeg** [comment] 2016-01-11 14:17
I have seach through the entire project, and I found the ignore func has not been implemented yet.

**Comment by Shougo** [comment] 2016-01-12 13:12
It is implemented, but it did not work well.
Fixed.

**Closed by Shougo** 2016-01-12 13:12 UTC

**Comment by lee-kagiso** [comment] 2016-01-12 14:11
Thanks, that did the trick
