### ISSUE TITLE
deoplete#mappings#manual_complete() doesn't work as expected

### ISSUE THREAD

**Issue by sodiumjoe** [Shougo/deoplete.nvim#136] opened 2016-01-22 05:42 UTC
Mac OS X

```bash
➤  vim --version
NVIM v0.1.2-300-gee0e214
Build type: RelWithDebInfo
Compilation: /opt/boxen/homebrew/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160119-49644-11dvzhi/build/config -I/tmp/neovim20160119-49644-11dvzhi/src -I/tmp/neovim20160119-49644-11dvzhi/deps-build/usr/include -I/tmp/neovim20160119-49644-11dvzhi/deps-build/usr/include -I/tmp/neovim20160119-49644-11dvzhi/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160119-49644-11dvzhi/deps-build/usr/include -I/tmp/neovim20160119-49644-11dvzhi/deps-build/usr/include -I/tmp/neovim20160119-49644-11dvzhi/deps-build/usr/include -I/tmp/neovim20160119-49644-11dvzhi/deps-build/usr/include -I/opt/boxen/homebrew/opt/gettext/include -I/usr/include -I/tmp/neovim20160119-49644-11dvzhi/build/src/nvim/auto -I/tmp/neovim20160119-49644-11dvzhi/build/include
Compiled by jmoon@jmoon

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/boxen/homebrew/Cellar/neovim/HEAD/share/nvim"

```

minimal `.vimrc`:

```VimL
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim'
call plug#end()

let g:deoplete#enable_at_startup = 1

inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
```

# Expected behavior

I expect `tab` key to work normally in insert mode.

# Actual behavior

`tab` key does nothing in insert mode, or brings up completion list.

**Comment by Shougo** [comment] 2016-01-22 20:47
It is your intended behavior.
Because, you map `<Tab>` key.
What's the problem?
Closing.

**Closed by Shougo** 2016-01-22 20:47 UTC

**Comment by sodiumjoe** [comment] 2016-01-23 04:16
sorry, i should've been more clear.

Since `deoplete#auto_completion_start_length` defaults to `2`, I assume the completion list shouldn't appear until i have typed two characters in insert mode. I thought `pumvisible() ?` meant that the tab remapping would only apply when the autocompletion selection popup was visible.

Basically, what I want is for tab to cycle through completion only when the popup window is visible (after typing two characters). Is this possible?

Thanks for your help, and thanks for the awesome plugin!

**Comment by sodiumjoe** [comment] 2016-01-23 05:07
nm, i figured it out. In case anyone else is trying to do the same:

```vimL
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
```

**Comment by Shougo** [comment] 2016-01-23 09:57
> Since deoplete#auto_completion_start_length defaults to 2, I assume the completion list shouldn't appear until i have typed two characters in insert mode. I thought pumvisible() ? meant that the tab remapping would only apply when the autocompletion selection popup was visible.

Manual completion ignores `deoplete#auto_completion_start_length`.
It is for the auto completion.
