### ISSUE TITLE
Better recovery in case Python channel is invalid

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#322] opened 2016-08-01 08:40 UTC
After the Neovim Python processes have been killed (e.g. `pkill -f "neovim.start"`), deoplete will trigger errors all the time, e.g.

```
Error detected while processing function <SNR>202_completion_begin:
line   29:
E475: Invalid argument: Channel doesn't exist
```

I've started looking into a way to recover from there (by wrapping `rpcnotify` and `rpcrequest`), but it seems like this needs to be done in Neovim, since deoplete just uses the `channel_id` from the `vim` instance, right?

However, if deoplete could re-establish a new channel this would be nice to have.

**Comment by tweekmonster** [comment] 2016-08-01 15:50
Yeah it looks like it needs to be resolved in Neovim.  It should make an attempt at restarting the host if it dies unexpectedly. 

<details>
<summary>Here's a diff of what I tried:</summary>
```diff
diff --git a/autoload/deoplete.vim b/autoload/deoplete.vim
index 96975fd..c35f4bd 100644
--- a/autoload/deoplete.vim
+++ b/autoload/deoplete.vim
@@ -4,6 +4,36 @@
 " License: MIT license
 "=============================================================================
 
+function! s:safe_rpc(meth, args) abort
+  try
+    let ret = call(a:meth, a:args)
+    unlet! s:_rpc_retry
+    return ret
+  catch /E475/
+    if !exists('s:_rpc_retry')
+      call deoplete#util#print_warning(
+            \ 'deoplete.nvim RPC channel lost.  restarting.')
+      let s:_rpc_retry = 1
+      unlet! g:deoplete#_channel_id
+      unlet! g:loaded_remote_plugins
+      call deoplete#init#_initialize()
+      return s:safe_rpc(a:meth, a:args)
+    else
+      unlet! s:_rpc_retry
+      call deoplete#util#print_warning(
+            \ 'deoplete.nvim RPC channel lost.  Restart attempt failed.')
+    endif
+  endtry
+endfunction
+
+function! deoplete#rpcnotify(...) abort
+  return s:safe_rpc('rpcnotify', a:000)
+endfunction
+
+function! deoplete#rpcrequest(...) abort
+  return s:safe_rpc('rpcrequest', a:000)
+endfunction
+
 function! deoplete#initialize() abort "{{{
   return deoplete#init#_initialize()
 endfunction"}}}
@@ -27,7 +57,7 @@ function! deoplete#enable_logging(level, logfile) abort "{{{
     return
   endif
 
-  call rpcrequest(g:deoplete#_channel_id,
+  call deoplete#rpcrequest(g:deoplete#_channel_id,
         \ 'deoplete_enable_logging', a:level, a:logfile)
 endfunction"}}}
 
diff --git a/autoload/deoplete/handler.vim b/autoload/deoplete/handler.vim
index 71475cc..8979774 100644
--- a/autoload/deoplete/handler.vim
+++ b/autoload/deoplete/handler.vim
@@ -76,7 +76,7 @@ function! s:completion_begin(event) abort "{{{
   endfor
 
   call deoplete#mapping#_set_completeopt()
-  call rpcnotify(g:deoplete#_channel_id,
+  call deoplete#rpcnotify(g:deoplete#_channel_id,
         \ 'deoplete_auto_completion_begin', context)
 endfunction"}}}
 function! s:is_skip(event, context) abort "{{{
@@ -142,7 +142,7 @@ endfunction"}}}
 
 function! s:on_event(event) abort "{{{
   let context = deoplete#init#_context(a:event, [])
-  call rpcnotify(g:deoplete#_channel_id, 'deoplete_on_event', context)
+  call deoplete#rpcnotify(g:deoplete#_channel_id, 'deoplete_on_event', context)
 endfunction"}}}
 
 function! s:on_insert_leave() abort "{{{
diff --git a/autoload/deoplete/mapping.vim b/autoload/deoplete/mapping.vim
index a14dd1d..0f10156 100644
--- a/autoload/deoplete/mapping.vim
+++ b/autoload/deoplete/mapping.vim
@@ -32,7 +32,7 @@ function! deoplete#mapping#_set_completeopt() abort "{{{
   endif
 endfunction"}}}
 function! deoplete#mapping#_rpcnotify_wrapper(sources) abort "{{{
-  call rpcrequest(g:deoplete#_channel_id,
+  call deoplete#rpcrequest(g:deoplete#_channel_id,
         \ 'deoplete_manual_completion_begin',
         \ deoplete#init#_context('Manual', a:sources))
   return ''
```
</details>

But, I think killing the process manually is an unlikely scenario that Deoplete shouldn't have to deal with.  I think a more realistic scenario is source plugins crashing from an unhandled exception.  Deopelete could catch those and disable the source after so many failures instead of letting the host process crash.

**Comment by Shougo** [comment] 2016-08-06 01:50
@tweekmonster Please use `deoplete#util#rpcnotiry()` instead `deoplete#rpcnotify()`.
`deoplete#rpcrequest()` has same problem.

And please create new PR for it.
I think `meth` is bad name.  It should be `method`.

**Comment by tweekmonster** [comment] 2016-08-06 02:10
@Shougo Sorry I forgot about this.  That was just a test to confirm the issue is inside of Neovim, not an actual fix.  I don't think it can be fixed in Deoplete.  When the host process crashes, there's no way to revive the process.  I think it will need to be fixed in `autoload/remote/host.vim`

The alternative is for `deoplete.py` to catch exceptions from a source and remove it if it produces too many errors.  I can look at refactoring how the sources are managed.

**Comment by Shougo** [comment] 2016-08-06 02:11
Hm.  OK.  It should be fixed when it is supported in host.vim.

**Closed by Shougo** 2016-08-06 02:11 UTC
Labels: wontfix

**Comment by blueyed** [comment] 2016-08-06 17:29
@tweekmonster 
Do you feel like bringing this up for Neovim?

**Comment by tweekmonster** [comment] 2016-08-06 17:42
@blueyed I was going to take a closer look at how it's handled in the remote scripts after https://github.com/neovim/neovim/pull/5050 was merged since it fixes the rplugin tests.

I'm also working on refactoring Deoplete today to catch source exceptions and log them instead of crashing.

**Comment by blueyed** [comment] 2016-09-21 23:08
@tweekmonster 
Any update in that regard?
I just remembered this issue, and we should at least track it with Neovim.

**Comment by tweekmonster** [comment] 2016-10-02 06:01
😱  Your last message just appeared in my email, but it was 10 days ago?!

I sort of forgot about doing something regarding this.  I did look into it a while ago, but will have to look through it again to refresh myself.  I think at the time, I felt that `remote#host#Require()` should do the channel polling (all of the provider scripts redundantly do it) and restart if it fails.  That way deoplete can just call `remote#host#Require('python3')` to get a new channel ID.  That would be the easiest approach without touching the C source.
