### ISSUE TITLE
Issues with fuzzy matching

### ISSUE THREAD

**Issue by kevincox** [Shougo/deoplete.nvim#938] opened 2019-02-16 10:06 UTC
# Problems summary

- Ranking is very poor with all-fuzzy when typing non-prefix matches.
- Not all results are available.

## Expected

- Fuzzy matching has good ranking and sees all results.

## Environment Information

 * deoplete version (SHA1): a588aee169f3b52a0382dc0289e883710f8f7f48

 * OS: Arch Linux

 * neovim/Vim `:version` output:

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconve
rsion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -s
td=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds
 -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/b
uild/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/buil
d/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

```
health#LanguageClient#check
========================================================================
  - OK: binary found: /home/kevincox/.cache/vim-plugins/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.140 

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5403'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.2
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v11.10.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#source('_', 'matchers', 'matcher_full_fuzzy')
```

Example js file:
```js
// fun ficticious fiction to create extra keywords Identifier expected.
window.foobar = 5;
window. 
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Trigger autocomplete. For example in the example js file I can type `window.`
1. Note that all methods are completed and sorted at the top of the suggestions.
1. Type in something fuzzy. Example `fb` to select `foobar`.
1. Notice that `foobar` is far down the list after non-matching items.
1. If there are enough words int he document after a moment `foobar` disappears from the list.

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/494012/53007057-676f5400-342e-11e9-82bd-8b1be66dbe87.png)

**Comment by kevincox** [comment] 2019-02-16 10:13
A partial workaround is the following which will solve the ranking issue by removing other candidates. However the issue of results being removed after a brief pause still happens. I guess if you type and think very fast this will work.

```vim
call deoplete#custom#option('sources', {'rust': ['LanguageClient']})
```

**Comment by Shougo** [comment] 2019-02-18 00:12
Your reproduce instructions are very poor.
I can close it.  Because it is not reproduce-able for me.

Please compare it with the other issues like this.
https://github.com/Shougo/deoplete.nvim/issues/934

You must upload the example file to reproduce the problem.

**Comment by Shougo** [comment] 2019-02-18 00:13
>     1. For example in a rust file I can type `self.`

This is very bad instruction.

**Comment by Shougo** [comment] 2019-02-18 00:14
And your minimal vimrc is not minimal.
Because you have installed LanguageClient-neovim.
But it is not included in the minimal vimrc.

I will close it.

**Comment by Shougo** [comment] 2019-02-18 00:16
You have already known:

> **Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

**Comment by kevincox** [comment] 2019-02-19 10:14
I have added languageclient to the vimrc and added an example js file to test.

**Comment by Shougo** [comment] 2019-02-19 23:40
I don't work for you.
Because you don't upload LanguageClient-neovim configuration.

> I have added languageclient to the vimrc and added an example js file to test.

Really?  It is reproduce-able with non project js file?
Most of LanguageClient does not work for non project directory.
You must describe it.

So I don't re-open this issue.
I am busy to fix other issues.  Other issues are easy to reproduce than yours.

**Comment by kevincox** [comment] 2019-02-20 07:15
> Because you don't upload LanguageClient-neovim configuration.

I did. The only configuration required is enabling a language server. 

It is reproducible with a non-projeft js file. That's why I switched to JS instead of rust, because it doesn't require setting up a project. As far as I can tell this issue occurs on any languageclient language though. 

> I don't work for you.

Of course you don't. That doesn't mean you should actually like an asshole. 

> So I don't re-open this issue.

Don't bother. I'll just use a plugin that has polite maintainers.

**Comment by Shougo** [comment] 2019-02-21 08:18
OK.  I will research for the problem.

> I did. The only configuration required is enabling a language server.

It is not just `only`.  It must be included in `minimal init.vim/vimrc`.
For example, you can fix LanguageClient-neovim problems without the configuration?

> It is reproducible with a non-project js file. That's why I switched to JS instead of rust, because it doesn't require setting up a project. As far as I can tell this issue occurs on any languageclient language though.

I need the information.  It is not described before, isn't it?

I should describe why I need exact information from you.
https://github.com/Shougo/echodoc.vim/issues/63

What do you think?

> Don't bother. I'll just use a plugin that has polite maintainers.

I am polite maintainer.  `Fixing problems` are very important for me.
So I need more information for you to fix bugs.

**Comment by Shougo** [comment] 2019-02-21 08:43
Reproduced.

**Comment by Shougo** [comment] 2019-02-21 08:53
OK.  I get the reason.

```vim
call deoplete#custom#source('_', 'matchers', ['matcher_full_fuzzy'])
```

matchers must be List.

So your matchers are disabled.

**Closed by Shougo** 2019-02-21 08:53 UTC
Labels: bug

**Comment by Shougo** [comment] 2019-02-21 08:54
You should read the examples in deoplete documentation.
All `matchers` custom usage is list.

**Comment by kevincox** [comment] 2019-02-21 09:25
Thanks. Would it be possible to get a better error message if the arguments are the wrong type? That would likely save users a lot of time.

**Comment by Shougo** [comment] 2019-02-21 10:04
I have checked the code.  And it seems not easy.

**Comment by Shougo** [comment] 2019-02-21 10:50
I have added type check for custom attrs.

**Comment by Shougo** [comment] 2019-02-21 10:51
You can test it in the latest version.
