### ISSUE TITLE
deoplete now automatically completes without permission

### ISSUE THREAD

**Issue by ExpandingMan** [Shougo/deoplete.nvim#1013] opened 2019-09-03 15:54 UTC
Seems to be exactly as in #440, but the problem is back.

Note this only seems to be in `master`, it seems fine in 5.1.  Unfortunately I am still using Vundle which always pulls master.

**Comment by Shougo** [comment] 2019-09-03 16:42
Please don't ignore issue template.
I can close the issue.

> Note this only seems to be in master, it seems fine in 5.1. Unfortunately I am still using Vundle which always pulls master.

Why don't you execute `git bisect`?

**Comment by Shougo** [comment] 2019-09-03 16:50
I think `git bisect` is easy.
Because, the diff is not so huge.

But I cannot execute `git bisect`.
I cannot reproduce the problem.

**Comment by Shougo** [comment] 2019-09-03 16:52
You need to upload the minimal vimrc with the reproducible instructions.
It is required to reproduce the problem.

**Comment by gfontenot** [comment] 2019-09-03 17:49
I'm seeing this as well. It's either because of something introduced in 93722cc5d0a1877fdad0845330b3a41c5e392a34 or 19a089acb7d007b0ad573eca1b5828740870816b. Reverting those two changes gets me back to the existing behavior.

**Comment by ExpandingMan** [comment] 2019-09-03 18:24
Sorry for not being more helpful, when I first posted this I was in a hurry and I figured the reference to the previous issue would be enough.

This happens for me on current master, but *not* on 5.1.  I can reproduce simply by typing in anything that brings up a deoplete completion box.  When doing so, very quickly the box will disappear as if the first (I think it's always the first) option was chosen.  Don't know exactly what commit it's coming from yet.

**Comment by conradob** [comment] 2019-09-03 21:16
I'm also facing this issue. Check the gif image (sorry for the wrong colors)
I didn't select any of these `const`

![ezgif-2-299742f151cd](https://user-images.githubusercontent.com/1469697/64209386-43d69d00-ce98-11e9-9acb-fb43e622260e.gif)

Example project:
https://github.com/rsslldnphy/nvim-typescript-issue

**Comment by agaryen** [comment] 2019-09-03 21:35
:+1:
Also, my completion box is trembling now, for some reason. As if the fetching was still in progress and never stopped.

**Comment by Shougo** [comment] 2019-09-03 23:55
OK.  I get it.

**Comment by JuanVqz** [comment] 2019-09-04 16:20
@ExpandingMan you should `git pull` the [last commit solve the problem](https://github.com/Shougo/deoplete.nvim/commit/93722cc5d0a1877fdad0845330b3a41c5e392a34#diff-368e186fe0312a870c3dac58c9638a48R179)

Regards thanks @Shougo

**Comment by good-idea** [comment] 2019-09-18 22:40
I'm getting similar behavior with the latest commit (`5176768`). Here is my .vimrc:

https://github.com/good-idea/dotfiles/blob/master/vim/vimrc.vim

It's hard to reproduce it exactly - but I believe it's the same issue. I'll be typing something like `return`, and it will autocomplete in the middle of my keystrokes, i.e. after typing just `ret`. As a result, I end up with something like `returnturn`.

If I clear the line and begin typing the same thing, it doesn't happen again - so I'm not sure exactly how to get it to happen consistently.

**Comment by Shougo** [comment] 2019-09-19 02:53
Unfortunately, I cannot fix the problem completely.
Deoplete is asynchronous completion plugin.
It way conflict with your input.

**Comment by Shougo** [comment] 2019-09-19 02:54
I think it is not related the problem.

**Comment by Shougo** [comment] 2019-09-19 03:00
You should create the minimal vimrc to reproduce the problem.

**Comment by good-idea** [comment] 2019-09-19 03:17
Thanks for your fast response, I'll put together a minimal vimrc tomorrow.

In the meantime, it looks like the conflict is only happening with the source from `nvim-typescript` ([repo](https://github.com/mhartington/nvim-typescript)). I deleted its `/rplugin/python3/deoplete/sources` and the issue has stopped.

**Comment by Shougo** [comment] 2019-09-19 03:22
nvim-typescript is asynchronous source and it may be conflicted.

**Comment by Shougo** [comment] 2019-09-19 12:14
@good-idea 

Please test the latest version of deoplete and #1018

**Comment by realcr** [comment] 2019-10-10 13:51
I have the same issue with rust language server, when using `LanguageClient-neovim`.
Sometimes deoplete autocompletes a word without my permission. I'm not yet sure what is the exact time that it happens.

**Comment by good-idea** [comment] 2019-10-10 18:06
@Shougo , sorry I never followed up from your last comment -
I'm still experiencing this issue. I have been trying to minimize my vimrc to show you something reproducible (or figure out if it is a problem with another plugin), but it's difficult because the problem doesn't occur at any specific time.
This mostly happens with my Typescript autocomplete (via nvim-typescript) but it did happen a couple other times when editing other types of files.

**Comment by Shougo** [comment] 2019-10-10 23:50
Please use the latest version of deoplete.
I have updated from the last comment.
If you don't upload the minimal, I don't work for you unfortunately.
Please read other issues.

**Comment by realcr** [comment] 2019-10-16 16:18
@Shougo : This is what I have in my vimrc:

```
" RLS related, see: https://github.com/autozimu/LanguageClient-neovim
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
" (Optional) Multi-entry selection UI.
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
```
I ran `PlugUpdate`. Does this mean that I am using the latest version of deoplete? If not, what should I do to use the latest version? I am still experiencing the problem.

I think that it is a good idea to reopen this issue. If other people are having the same problem it might be helpful if they can find this issue too.

**Comment by Shougo** [comment] 2019-10-17 00:53
> I ran PlugUpdate. Does this mean that I am using the latest version of deoplete?

Yes.  But you should check deoplete's commit hash.

> This is what I have in my vimrc:

This is not the minimal vimrc I have desired.

> I think that it is a good idea to reopen this issue. If other people are having the same problem it might be helpful if they can find this issue too.

Hmm..  I can reopen this.
But I don't work for the problem without minimal vimrc and reproduce instructions.

**Comment by Shougo** [comment] 2019-10-17 00:55
@realcr Please read the issue.

https://github.com/Shougo/deoplete.nvim/issues/1026

You need to provide more information.

**Comment by dnguyen85** [comment] 2019-12-17 23:19
@Shougo: I have the same issue with the latest version of deoplete with `Clangd` language server, when using `LanguageClient-neovim`. deoplete frequently autocompletes a word without my permission. I have found that if I set `call deoplete#custom#option({'auto_complete_delay' : 50,})`, the issue mostly goes away. However, this setting does significantly slow down completion suggestions from `LanguageClient-neovim`.

**Comment by Shougo** [comment] 2019-12-17 23:33
Hm.

https://github.com/Shougo/deoplete.nvim/issues/1013#issuecomment-542780551

LanguageClient-neovim is also asynchronous plugin.
It may be conflicted.

**Comment by Shougo** [comment] 2019-12-17 23:42
https://github.com/autozimu/LanguageClient-neovim/blob/next/rplugin/python3/deoplete/sources/LanguageClientSource.py#L29

Deprecated `is_async` source feature seems affected.

**Comment by Shougo** [comment] 2019-12-17 23:47
I think the documentation should be updated.

**Comment by Shougo** [comment] 2019-12-18 00:09
@dnguyen85 What is your Vim/neovim version?

**Comment by Shougo** [comment] 2019-12-18 00:18
Please test the latest version of deoplete and Vim/neovim.

I have added selected check.  It may fix the problem.

**Comment by Shougo** [comment] 2019-12-18 00:35
@dnguyen85 Please test git bisect.  I may implement good fallback system for it.

**Comment by mikijov** [comment] 2020-03-15 15:07
Hi @Shougo. Firstly, thank you very much for the many awesome vim plugins. Much appreciated.

It seems that you cannot nicely reproduce this. Here is the smallest .vimrc I could make to reproduce this reliably.

```
"NeoBundle Scripts-----------------------------
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif
endif

if has('eval') " load plugins only if running full vim
  call plug#begin('~/.vim/plugged')

    " dark powered neo-complete
    if has('nvim')
      Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    else
      Plug 'Shougo/deoplete.nvim'
      Plug 'roxma/nvim-yarp'
      " On arch vim-hug requires greenlet which needs to be install using pacman and
      " not pip. "pacman -S python-greenlet"
      Plug 'roxma/vim-hug-neovim-rpc'
    endif

    Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoUpdateBinaries' }

  " Required:
  call plug#end()
endif

syntax enable
set smartindent
set autoindent
nmap <SPACE> :
imap jj <ESC>
autocmd FileType go setlocal noexpandtab shiftwidth=4 tabstop=4 softtabstop=4

" Deoplete
let g:deoplete#enable_at_startup = 1
" This instructs deoplete to use omni completion for Go files. omni is provided by vim-go
call deoplete#custom#option('omni_patterns', { 'go': '[^. *\t]\.\w*' })

" vim-go
let g:go_code_completion_enabled = 1
let g:go_auto_type_info = 1
let g:go_doc_popup_window = 1
let g:go_metalinter_autosave = 0
let g:go_fmt_fail_silently = 1
" Set all output to "quickfix" or "locationlist"
let g:go_list_type = "quickfix"
let g:go_list_type_commands = {"GoBuild":"quickfix"}
let g:go_highlight_space_tab_error = 1

" autocomplete with longest common portion, then show alternatives in a menu
set completeopt=menu

imap <expr><TAB>
  \ pumvisible() ? "\<C-n>" :
  \ "\<TAB>"
smap <expr><TAB>
  \ pumvisible() ? "\<C-n>" :
  \ "\<TAB>"
imap <expr><S-TAB>
  \ pumvisible() ? "\<C-p>" :
  \ "\<S-TAB>"
smap <expr><TAB>
  \ pumvisible() ? "\<C-p>" :
  \ "\<TAB>"
imap <expr><CR>
  \ pumvisible() ? "\<C-y>" :
  \ "\<CR>"
smap <expr><CR>
  \ pumvisible() ? "\<C-y>" :
  \ "\<CR>"

" update interval for gitgutter and similar
set updatetime=250
```

To reproduce, you will also need a source file. Here is small `test.go`
```
package main

type Dummy interface {
	One()
	Two()
	Three()
}

func main() {
	var a Dummy
	var b Dummy
	var c Dummy
	var d Dummy
	var e Dummy

	a.One()
	b.One()
	c.One()
	d.One()
	e.One()
}
```

Steps to reproduce:
- $ vim test.go
- navigate to 16,4
- `cwTwo` - this is the line when the problem occurs; about 50% of the time I get `a.Two()` and other `a.OneTwo()`

I also get another problem, which I think is related:
- $ vim test.go
- navigate to 16,4
- `*` - this will move cursor to 17,4
- `cwTwo` - this will replace 17,4 to `a.Two()`
- `*.` - this will replace 18,4 to `c.Two()`
- `*.` - this will leave 19,4 to `d.One()`
- `*.` - this will leave 20,4 to `e.One()`

**Comment by Shougo** [comment] 2020-03-16 00:08
I will test it later.  But omni_patterns may be conflicted with deoplete.
It is used for deprecated plugins.

**Comment by Shougo** [comment] 2020-03-17 11:53
Reproduced.  You need to set noselect.

```vim
set completeopt=menu,noselect
```

**Comment by Shougo** [comment] 2020-03-17 11:56
deoplete now checks completeopt value.

**Comment by mikijov** [comment] 2020-04-26 14:48
Thanks @Shougo, `noselect` solves the original problem where autocomplete completes unintentionally. 

In my description above, I also show another problem, which I thought was related, but it still persists after `noselect`. Search for `cwTwo` in my comment. Do you want me to re-post it as a separate issue?

**Comment by Shougo** [comment] 2020-04-26 15:52
You need to create new issue with minimal vimrc.
Your uploaded vimrc is not real minimal vimrc.
You need to more reduce the code.

**Closed** 2020-06-18 23:33 UTC
Labels: needs reproduction instructions, source problem

**Comment by j5shi** [comment] 2021-09-06 08:53
@Shougo what's your avatar? Is it fish? Just curious...

**Comment by Shougo** [comment] 2021-09-06 10:59
Well.  It is FAQ.  It is not fish or zebra.
It is the dark dragon knight's head.

**Comment by j5shi** [comment] 2021-09-06 15:17
> Well. It is FAQ. It is not fish or zebra.
> It is the dark dragon knight's head.

Interesting...I was thinking it might be lionfish and that idea would come to my mind every time I see your avatar  -_-!

**Comment by Shougo** [comment] 2021-09-06 22:19
> Interesting...I was thinking it might be lionfish and that idea would come to my mind every time I see your avatar -_-!

Lol
